export type Relationship = { personKey:string;telegramUserId:number;displayName:string;username:string|null;identityStatus:string;buyerStatus:string|null;lifetimeVerifiedRevenueMinor:number|null;qualifyingPurchaseCount:number|null;latestActivityAt:string;latestMessagePreview:string|null;latestSpeaker?:"CUSTOMER"|"AVA"|null;activePurchaseIntent:boolean;activeSalesSession:boolean;controlMode?:"AVA_AUTO"|"HUMAN_OPERATOR";needsAttention?:boolean;isBuyer?:boolean;lastCustomerInboundAt?:string|null;lastVisibleOutboundAt?:string|null };
export type RelationshipMessage = { eventKey:string;direction:"CUSTOMER"|"AVA";content:string;timestamp:string;telegramMessageId:number|null;messageType:string;purchaseIntentId:string|null;origin?:"AI"|"HUMAN_OPERATOR" };
export type RelationshipControl = {mode:"AVA_AUTO"|"HUMAN_OPERATOR";controlVersion:number;changedAt:string|null;changedBy:string;reason:string|null;lastManualActivityAt:string|null;activePurchaseIntent:boolean;activeSalesSession:boolean};
export type RelationshipSort = "LATEST_ACTIVITY"|"LIFETIME_SPEND";
export type RelationshipFilter = "ALL"|"NEEDS_ATTENTION"|"BUYERS"|"PROSPECTS"|"MANUAL"|"ACTIVE_SESSION"|"ACTIVE_INTENT";
export type RelationshipSummary = {total:number;needsAttention:number;buyers:number;prospects:number;manual:number};
export type RelationshipList = { items:Relationship[];nextCursor:string|null;hasMore:boolean;sort:RelationshipSort;filter?:RelationshipFilter;summary?:RelationshipSummary };
export type Transcript = { person:Relationship;items:RelationshipMessage[];olderCursor:string|null;hasMoreOlder:boolean };
export type IntelligenceOffer = {title:string;type:string|null;priceMinor:number|null;presentedAt?:string|null;purchasedAt?:string|null;status?:string;ownershipStatus?:string};
export type RelationshipIntelligence = {person:Relationship;mappingStatus:"VERIFIED"|"UNMAPPED";partial:boolean;customerValue:{buyerStatus:string;valueTier:string|null;attentionTier:string|null;lifetimeSpendMinor:number|null;purchaseCount:number|null;repeatBuyer:boolean;relationshipLifecycle:string};salesPerformance:{offersPresented:number;offersPurchased:number;offersNotPurchased:number;conversionRate:number|null;lastOffer:IntelligenceOffer|null;lastPurchase:IntelligenceOffer|null};commercialState:{activePurchaseIntent:IntelligenceOffer|null;activeSalesSession:{state:string;stage:string;type:string|null}|null;activeOffer:IntelligenceOffer|null};purchaseHistory:IntelligenceOffer[];relationshipIntelligence:{location:string|null;timezone:string|null;interests:string[];pets:string[];music:string[];preferences:string[]}};
export type OfferCard={offeringId:string;title:string;description:string|null;type:string;priceMinor:number;currency:string;thumbnailUrl:string;status:"AVAILABLE"|"OFFERED_BEFORE"|"ACTIVE_OFFER"|"PURCHASED";owned:boolean;eligible:boolean;presentationCount:number;recommended:boolean;activePurchaseIntentId:string|null};
export type OfferInventory={items:OfferCard[];view:string;hidePurchased:boolean;businessConnectionId:string|null};
export type PreparedOffer={offering:Pick<OfferCard,"offeringId"|"title"|"type"|"priceMinor"|"currency"|"thumbnailUrl">;businessConnectionId:string;controlVersion:number;defaultMessage:string};

async function read<T>(path:string,signal?:AbortSignal):Promise<T>{const response=await fetch(path,{cache:"no-store",signal});const body=await response.json() as T&{detail?:string};if(!response.ok)throw new Error(body.detail||"Unable to load Chat.");return body;}
async function command<T>(path:string,body:unknown):Promise<T>{const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as T&{detail?:string};if(!response.ok)throw new Error(result.detail||"Relationship command failed.");return result;}
export const relationshipsApi={
  list:(search="",sort:RelationshipSort="LATEST_ACTIVITY",filter:RelationshipFilter="ALL",cursor?:string|null,signal?:AbortSignal)=>{const query=new URLSearchParams({limit:"50",sort,filter});if(search)query.set("search",search);if(cursor)query.set("cursor",cursor);return read<RelationshipList>(`/api/v1/relationships?${query}`,signal);},
  messages:(key:string,cursor?:string|null,signal?:AbortSignal)=>{const query=new URLSearchParams({limit:"50"});if(cursor)query.set("cursor",cursor);return read<Transcript>(`/api/v1/relationships/${encodeURIComponent(key)}/messages?${query}`,signal);},
  intelligence:(key:string,signal?:AbortSignal)=>read<RelationshipIntelligence>(`/api/v1/relationships/${encodeURIComponent(key)}/intelligence`,signal),
  control:(key:string,signal?:AbortSignal)=>read<RelationshipControl>(`/api/v1/relationships/${encodeURIComponent(key)}/control`,signal),
  takeover:(key:string)=>command<RelationshipControl>(`/api/v1/relationships/${encodeURIComponent(key)}/takeover`,{}),
  returnToAva:(key:string)=>command<RelationshipControl>(`/api/v1/relationships/${encodeURIComponent(key)}/return-to-ava`,{}),
  send:(key:string,text:string,idempotencyKey:string,expectedControlVersion:number)=>command<RelationshipMessage&{state:string}>(`/api/v1/relationships/${encodeURIComponent(key)}/messages`,{text,idempotencyKey,expectedControlVersion}),
  offerInventory:(key:string,view:string,type:string,search:string,hidePurchased:boolean)=>{const query=new URLSearchParams({view,search,hidePurchased:String(hidePurchased)});if(type)query.set("type",type);return read<OfferInventory>(`/api/v1/relationships/${encodeURIComponent(key)}/offer-inventory?${query}`)},
  prepareOffer:(key:string,offeringId:string,expectedControlVersion:number,businessConnectionId:string)=>command<PreparedOffer>(`/api/v1/relationships/${encodeURIComponent(key)}/offers/prepare`,{offeringId,expectedControlVersion,businessConnectionId}),
  sendOffer:(key:string,body:{offeringId:string;expectedControlVersion:number;businessConnectionId:string;text:string;idempotencyKey:string})=>command<RelationshipMessage&{state:string}>(`/api/v1/relationships/${encodeURIComponent(key)}/offers`,body),
};
