import {fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {afterEach,expect,it,vi} from "vitest";
import {RelationshipsPage} from "./RelationshipsPage";
import type {Relationship} from "./api";

const prospect:Relationship={personKey:"telegram:2:2:7001352017",telegramUserId:7001352017,displayName:"Novi Fixture",username:null,identityStatus:"UNMAPPED",buyerStatus:null,isBuyer:false,lifetimeVerifiedRevenueMinor:null,qualifyingPurchaseCount:null,latestActivityAt:"2026-09-14T20:00:00Z",latestMessagePreview:"hello",activePurchaseIntent:false,activeSalesSession:false,controlMode:"AVA_AUTO",marketTier:"UNCLASSIFIED"};
const buyer={...prospect,personKey:"telegram:2:2:6392572491",telegramUserId:6392572491,displayName:"Wally Fixture",identityStatus:"MAPPED_VERIFIED",buyerStatus:"VERIFIED_BUYER",isBuyer:true,qualifyingPurchaseCount:5,lifetimeVerifiedRevenueMinor:11996};
const intelligence=(person=prospect,hvp=false)=>({person,mappingStatus:person.isBuyer?"VERIFIED":"UNMAPPED",partial:!person.isBuyer,operatorClassification:hvp?"HIGH_VALUE_PROSPECT":null,effectiveAttentionPriority:hvp?"PRIORITIZED":"STANDARD",behavioralIntelligence:{buyingIntent:"NONE",currentSignal:"NONE",salesStage:person.isBuyer?"CUSTOMER":"PROSPECT"},customerValue:{buyerStatus:person.isBuyer?"VERIFIED_BUYER":"UNMAPPED_PROSPECT",valueTier:person.isBuyer?"REPEAT_BUYER":"PROSPECT",attentionTier:"STANDARD",lifetimeSpendMinor:person.lifetimeVerifiedRevenueMinor,purchaseCount:person.qualifyingPurchaseCount,repeatBuyer:Boolean(person.isBuyer),relationshipLifecycle:person.isBuyer?"CUSTOMER":"PROSPECT",relationshipInvestment:"STANDARD",continuationValue:"STANDARD",timeWasterRisk:"NONE",retention:"NONE"},salesPerformance:{offersPresented:0,offersPurchased:0,offersNotPurchased:0,conversionRate:null,lastOffer:null,lastPurchase:null},commercialState:{activePurchaseIntent:null,activeSalesSession:null,activeOffer:null},purchaseHistory:[],relationshipIntelligence:{location:null,timezone:null,interests:[],pets:[],music:[],preferences:[]}});
const ok=(body:unknown)=>Promise.resolve(new Response(JSON.stringify(body),{status:200,headers:{"Content-Type":"application/json"}}));
function mock(person=prospect,failTier=false){let tier="UNCLASSIFIED",hvp=false;return vi.spyOn(globalThis,"fetch").mockImplementation((input,init={})=>{const url=String(input);if(url.includes("/messages?"))return ok({person,items:[],olderCursor:null,hasMoreOlder:false});if(url.includes("/control"))return ok({mode:"AVA_AUTO",controlVersion:0,activePurchaseIntent:false,activeSalesSession:false});if(url.includes("/intelligence"))return ok(intelligence(person,hvp));if(url.includes("/market-tier")){if(init.method==="PUT"){if(failTier)return Promise.resolve(new Response(JSON.stringify({detail:"Rejected"}),{status:409,headers:{"Content-Type":"application/json"}}));tier=JSON.parse(String(init.body)).marketTier;}if(init.method==="DELETE")tier="UNCLASSIFIED";return ok({marketTier:tier,effectiveProspectInvestment:"STANDARD",highValueProspect:hvp,verifiedBuyer:Boolean(person.isBuyer),repliesUsedToday:0,dailyReplyBudget:null,budgetStatus:"AVAILABLE",nextBudgetResetAt:null,prospectReplyLimit:person.isBuyer?"NOT_APPLICABLE":null});}if(url.includes("/operator-classification")){hvp=init.method!=="DELETE";return ok({intelligence:intelligence(person,hvp),scheduling:{scheduleAdvanced:false,advancedOperation:null}});}return ok({items:[person],nextCursor:null,hasMore:false,summary:{total:1,needsAttention:0,buyers:person.isBuyer?1:0,prospects:person.isBuyer?0:1,manual:0}});});}
afterEach(()=>{vi.restoreAllMocks();Object.defineProperty(window,"innerWidth",{configurable:true,value:1024});Object.defineProperty(window,"innerHeight",{configurable:true,value:768});});

it("renders MORE in a viewport portal and supports focus, outside click, and Escape",async()=>{
 const fetchMock=mock();fetchMock.mockImplementation((input)=>{const url=String(input);if(url.includes("/messages?"))return ok({person:prospect,items:[{eventKey:"visible",direction:"CUSTOMER",content:"hello",timestamp:"2026-09-14T20:00:00Z",telegramMessageId:1,messageType:"ORDINARY_CHAT",purchaseIntentId:null}],olderCursor:null,hasMoreOlder:false});if(url.includes("/control"))return ok({mode:"AVA_AUTO",controlVersion:0,activePurchaseIntent:false,activeSalesSession:false});if(url.includes("/intelligence"))return ok(intelligence());if(url.includes("/market-tier"))return ok({marketTier:"UNCLASSIFIED",effectiveProspectInvestment:"STANDARD",highValueProspect:false,verifiedBuyer:false,repliesUsedToday:0,dailyReplyBudget:null,budgetStatus:"AVAILABLE",nextBudgetResetAt:null,prospectReplyLimit:null});return ok({items:[prospect],nextCursor:null,hasMore:false,summary:{total:1,needsAttention:0,buyers:0,prospects:1,manual:0}});});render(<RelationshipsPage/>);fireEvent.click(await screen.findByRole("button",{name:/Novi Fixture/}));const trigger=await screen.findByRole("button",{name:"More conversation controls"});
 expect(screen.getByRole("button",{name:"TAKE OVER"})).toBeInTheDocument();fireEvent.click(trigger);let menu=screen.getByRole("menu",{name:"More conversation controls"});expect(menu.parentElement).toBe(document.body);expect(menu).toHaveClass("conversation-popup-menu");expect(menu.style.position).toBe("");await waitFor(()=>expect(within(menu).getByRole("menuitem",{name:"HIGH"})).toHaveFocus());expect(within(menu).queryByRole("menuitem",{name:"Take Over"})).not.toBeInTheDocument();expect(within(menu).getByRole("menuitem",{name:"Ignore Relationship"})).toBeInTheDocument();expect(within(menu).getByText("Transcript")).toBeInTheDocument();expect(within(menu).getByRole("menuitem",{name:"Download Chat"})).toBeEnabled();expect(Number.parseFloat(menu.style.maxHeight)).toBeGreaterThan(0);
 fireEvent.pointerDown(document.body);expect(screen.queryByRole("menu",{name:"More conversation controls"})).not.toBeInTheDocument();fireEvent.click(trigger);fireEvent.keyDown(document,{key:"Escape"});expect(screen.queryByRole("menu",{name:"More conversation controls"})).not.toBeInTheDocument();expect(trigger).toHaveFocus();
});

it.each([[prospect,"PROSPECT"],[buyer,"CUSTOMER"]] as const)("exposes existing classifications for %s without lifecycle mutation",async(person,lifecycle)=>{
 const fetchMock=mock(person);Object.defineProperty(window,"innerWidth",{configurable:true,value:640});Object.defineProperty(window,"innerHeight",{configurable:true,value:520});render(<RelationshipsPage/>);fireEvent.click(await screen.findByRole("button",{name:new RegExp(person.displayName)}));expect((await screen.findAllByText(lifecycle)).length).toBeGreaterThan(0);const trigger=await screen.findByRole("button",{name:"Classify relationship"});fireEvent.click(trigger);const menu=screen.getByRole("menu",{name:"Classify relationship"});expect(menu.parentElement).toBe(document.body);for(const label of ["HIGH","MED","LOW","UNCLASSIFIED"])expect(within(menu).getByRole("menuitem",{name:label})).toBeInTheDocument();expect(within(menu).getByRole("menuitem",{name:"High Value Prospect: OFF"})).toBeInTheDocument();fireEvent.click(within(menu).getByRole("menuitem",{name:"HIGH"}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url,init])=>String(url).includes("/market-tier")&&init?.method==="PUT")).toBe(true));expect(screen.getAllByText(lifecycle).length).toBeGreaterThan(0);expect(screen.queryByText(/Make Customer|Make Prospect/)).not.toBeInTheDocument();
});

it("keeps the authoritative unclassified state when a classification write fails",async()=>{
 mock(prospect,true);render(<RelationshipsPage/>);fireEvent.click(await screen.findByRole("button",{name:/Novi Fixture/}));fireEvent.click(await screen.findByRole("button",{name:"Classify relationship"}));fireEvent.click(screen.getByRole("menuitem",{name:"HIGH"}));await screen.findByRole("alert");expect(screen.queryByTitle("Market Tier HIGH")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Classify relationship"}));expect(screen.getByRole("menuitem",{name:"UNCLASSIFIED"})).toHaveAttribute("aria-pressed","true");
});
