import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {ConversationAnalysisDialog} from "./ConversationAnalysisDialog";
import {relationshipsApi} from "./api";
vi.mock("./api",async()=>{const actual=await vi.importActual<typeof import("./api")>("./api");return {...actual,relationshipsApi:{...actual.relationshipsApi,analyzeConversation:vi.fn(),createRepairProposal:vi.fn(),approveRepairProposal:vi.fn(),executeRepair:vi.fn(),repairExecution:vi.fn()}}});
const finding=(scope="CONVERSATION_ONLY")=>({findingId:"f1",targetMessageReference:"m1",severity:"MATERIAL" as const,category:"CONTEXTUAL_RELEVANCE",whatHappened:"Availability language answered a compliment.",whyItIsProblematic:"The response was irrelevant.",rootCauseCategory:"COMMERCIAL_CLASSIFICATION",validatedScope:scope as "CONVERSATION_ONLY",confidence:.9,similarCaseCount:scope==="CONVERSATION_ONLY"?0:3,suggestedCorrection:"Require current commercial evidence.",repairCandidate:scope!=="CONVERSATION_ONLY"});
const response=(scope="CONVERSATION_ONLY")=>({analysisId:"a1",staleState:"CURRENT" as const,analysis:{overallQuality:"MATERIAL",conversationSummary:"Mismatch found.",operatorSummary:"Review.",validatedScope:scope,globalRepairCandidate:scope!=="CONVERSATION_ONLY"},findings:[finding(scope)],similarCaseSummary:{similarCaseCount:0}});
const proposal={proposal_id:"p1",analysis_id:"a1",finding_id:"f1",validated_scope:"GLOBAL_SYSTEM",root_cause_category:"COMMERCIAL_CLASSIFICATION",failure_signature:"SIG",affected_relationship_count:4,violated_invariant:"bad",proposed_invariant:"Require current evidence",expected_effect:"fixed",preserved_behavior:["Price inquiry"],known_risks:["risk"],regression_requirements:["Original fixed"],repair_category:"COMMERCIAL_CLASSIFICATION_POLICY",risk:"HIGH",created_at:new Date().toISOString(),expires_at:new Date(Date.now()+60000).toISOString(),status:"PROPOSED"};
async function reachApproval(){render(<ConversationAnalysisDialog personKey="p" onClose={()=>{}}/>);fireEvent.click(screen.getByText("Analyze Entire Conversation"));fireEvent.click(await screen.findByRole("button",{name:"REVIEW REPAIR"}));fireEvent.click(await screen.findByRole("button",{name:"APPROVE"}));fireEvent.click(screen.getByRole("button",{name:"Confirm Approval"}));}
describe("ConversationAnalysisDialog",()=>{beforeEach(()=>vi.clearAllMocks());
 it("shows Download only after analysis and does not analyze again when clicked",async()=>{const createObjectURL=vi.fn(()=>"blob:test");Object.defineProperty(URL,"createObjectURL",{configurable:true,value:createObjectURL});Object.defineProperty(URL,"revokeObjectURL",{configurable:true,value:vi.fn()});vi.spyOn(HTMLAnchorElement.prototype,"click").mockImplementation(()=>{});vi.mocked(relationshipsApi.analyzeConversation).mockResolvedValue(response());render(<ConversationAnalysisDialog personKey="p" displayName="Johnny" onClose={()=>{}}/>);expect(screen.queryByRole("button",{name:"Download"})).not.toBeInTheDocument();fireEvent.click(screen.getByText("Analyze Entire Conversation"));fireEvent.click(await screen.findByRole("button",{name:"Download"}));fireEvent.click(screen.getByRole("button",{name:"Download"}));expect(relationshipsApi.analyzeConversation).toHaveBeenCalledTimes(1);expect(createObjectURL).toHaveBeenCalledTimes(2);});
 it("hides repair for one-off scope",async()=>{vi.mocked(relationshipsApi.analyzeConversation).mockResolvedValue(response());render(<ConversationAnalysisDialog personKey="p" onClose={()=>{}}/>);fireEvent.click(screen.getByText("Analyze Entire Conversation"));expect(await screen.findByText(/GLOBAL REPAIR.*NOT RECOMMENDED/)).toBeInTheDocument();expect(screen.queryByRole("button",{name:"REVIEW REPAIR"})).not.toBeInTheDocument();});
 it("keeps production execution disabled",async()=>{vi.mocked(relationshipsApi.analyzeConversation).mockResolvedValue(response("GLOBAL_SYSTEM"));vi.mocked(relationshipsApi.createRepairProposal).mockResolvedValue({scope:"GLOBAL_SYSTEM",globalRepair:"CANDIDATE",proposal});vi.mocked(relationshipsApi.approveRepairProposal).mockResolvedValue({authorization:{authorization_id:"z1"},status:"APPROVED_FOR_EXECUTION"});vi.mocked(relationshipsApi.executeRepair).mockRejectedValue(new Error("CONVERSATION REPAIR EXECUTION DISABLED"));await reachApproval();await waitFor(()=>expect(relationshipsApi.executeRepair).toHaveBeenCalledWith("p","z1"));expect(await screen.findByText("REPAIR EXECUTION DISABLED")).toBeInTheDocument();});
 it("renders READY evidence with no deploy action",async()=>{vi.mocked(relationshipsApi.analyzeConversation).mockResolvedValue(response("GLOBAL_SYSTEM"));vi.mocked(relationshipsApi.createRepairProposal).mockResolvedValue({scope:"GLOBAL_SYSTEM",globalRepair:"CANDIDATE",proposal});vi.mocked(relationshipsApi.approveRepairProposal).mockResolvedValue({authorization:{authorization_id:"z1"},status:"APPROVED_FOR_EXECUTION"});vi.mocked(relationshipsApi.executeRepair).mockResolvedValue({execution_id:"e1",state:"READY_FOR_DEPLOYMENT",workflow:"COMMERCIAL_CLASSIFICATION_POLICY",baseline_sha:"5".repeat(40),files_changed:["app/services/commercial_receptiveness_service.py"],tests_result:{passed:true},failure_reason:null,ready_for_deployment_at:new Date().toISOString()});await reachApproval();expect(await screen.findByText(/REPAIR TESTED — READY FOR DEPLOYMENT/)).toHaveTextContent(/Regression result: PASS/);expect(screen.queryByRole("button",{name:/deploy/i})).not.toBeInTheDocument();});
});
