import {fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
import {StrictMode} from "react";
import {InspectResolveDialog} from "./InspectResolveDialog";
import {relationshipsApi,type AttentionInspectionResponse,type AttentionScope,type Relationship} from "./api";

const person:Relationship={personKey:"fixture-j",telegramUserId:101,displayName:"Fixture J",username:null,identityStatus:"PROSPECT",buyerStatus:null,lifetimeVerifiedRevenueMinor:null,qualifyingPurchaseCount:null,latestActivityAt:"2026-09-13T12:00:00Z",latestMessagePreview:null,activePurchaseIntent:false,activeSalesSession:false,operationalStatus:"NEEDS_ATTENTION",attentionOccurrenceId:"occ-j"};
function response(scope:AttentionScope="CUSTOMER_ONLY",overrides:Partial<AttentionInspectionResponse["result"]>={}):AttentionInspectionResponse{return {inspection:{inspection_id:"inspect-1"},result:{schemaVersion:"V1",inspectionId:"inspect-1",relationshipKey:"fixture-j",attentionOccurrenceId:"occ-j",inspectedAt:"2026-09-13T12:00:00Z",whyFlagged:"A required reply failed quality review.",currentImpact:"The customer has no approved reply.",currentObligation:"Review the current obligation.",willAvaContinueAutomatically:false,avaAutoState:"ON",currentOperationState:"NO_FURTHER_AUTOMATIC_ATTEMPT",isConditionStillRelevant:true,rootCauseScope:scope,rootCauseSummary:"Customer-scoped quality failure.",affectedCurrentCustomersCount:scope==="MULTIPLE_CUSTOMERS"?3:1,similarCurrentCases:[],futureCustomersPotentiallyAffected:scope==="GLOBAL_SYSTEM",globalRepairAlreadyExists:false,recommendedResolutionType:scope==="GLOBAL_SYSTEM"?"ESCALATE_GLOBAL_REPAIR":scope==="AMBIGUOUS"?"NO_AUTOMATED_RESOLUTION":"ACKNOWLEDGE_ONLY",recommendedResolutionSummary:"Acknowledge the current occurrence.",operatorExplanation:"The current operation will not retry itself.",exactProposedActions:["Acknowledge this occurrence only."],customerVisibleSendPossible:false,providerGenerationPossible:false,databaseChangeRequired:true,riskLevel:"LOW",approvalRequired:scope==="CUSTOMER_ONLY"||scope==="MULTIPLE_CUSTOMERS",dispositionReason:null,confidence:.95,inspectionWarnings:[],cannotSafelyResolveReason:scope==="AMBIGUOUS"?"Evidence conflicts.":null,...overrides},plan:scope==="CUSTOMER_ONLY"||scope==="MULTIPLE_CUSTOMERS"?{plan_id:"plan-1",inspection_id:"inspect-1",relationship_key:"fixture-j",attention_occurrence_id:"occ-j",root_cause_scope:scope,action_type:"ACKNOWLEDGE_ONLY",approval_state:"PENDING",execution_state:"NOT_STARTED",provider_generation_possible:false,customer_visible_send_possible:false,risk_level:"LOW",expires_at:"2026-09-13T12:15:00Z"}:null};}
function setup(value=response(),props:Partial<React.ComponentProps<typeof InspectResolveDialog>>={}){vi.spyOn(relationshipsApi,"inspectAttention").mockResolvedValue(value);return render(<InspectResolveDialog target={person} occurrenceId="occ-j" onClose={vi.fn()} onResolved={vi.fn()} {...props}/>);}
afterEach(()=>vi.restoreAllMocks());

describe("Inspect & Resolve",()=>{
 it("opens read-only, then shows bounded business evidence",async()=>{setup();expect(screen.getByRole("status")).toHaveTextContent("read-only");expect(await screen.findByText("Why it was flagged")).toBeInTheDocument();expect(screen.getByText("Current impact")).toBeInTheDocument();expect(screen.getByText("Ava Auto: On")).toBeInTheDocument();expect(screen.getByText("Current Operation: No Further Automatic Attempt")).toBeInTheDocument();expect(screen.getByText("Inspected 7:00 AM")).toBeInTheDocument();expect(screen.queryByText("stateFingerprint")).not.toBeInTheDocument();});
 it("warns prominently before provider work or a customer-visible send",async()=>{setup(response("CUSTOMER_ONLY",{providerGenerationPossible:true,customerVisibleSendPossible:true,recommendedResolutionType:"REQUEUE_CORRECTIVE_REPLY"}));expect(await screen.findByRole("alert")).toHaveTextContent("customer-visible send");expect(screen.getByRole("alert")).toHaveTextContent("AI provider");});
 it("requires final confirmation and executes only the exact persisted plan",async()=>{vi.spyOn(relationshipsApi,"approveAttentionPlan").mockResolvedValue({...response().plan!,approval_state:"APPROVED"});vi.spyOn(relationshipsApi,"executeAttentionPlan").mockResolvedValue({execution_id:"exec-1",plan_id:"plan-1",action_type:"ACKNOWLEDGE_ONLY",status:"SUCCEEDED",result:{},completed_at:"2026-09-13T12:01:00Z"});const resolved=vi.fn();setup(response(),{onResolved:resolved});fireEvent.click(await screen.findByRole("button",{name:"Approve Resolution"}));const confirm=screen.getByRole("alertdialog");expect(confirm).toHaveTextContent("Fixture J only");fireEvent.click(within(confirm).getByRole("button",{name:"Confirm & Execute"}));await waitFor(()=>expect(relationshipsApi.approveAttentionPlan).toHaveBeenCalledWith("fixture-j","plan-1"));expect(relationshipsApi.executeAttentionPlan).toHaveBeenCalledWith("fixture-j","plan-1");expect(await screen.findByText("Attention acknowledged.")).toBeInTheDocument();expect(resolved).toHaveBeenCalledOnce();});
 it("does not claim a requeued reply was sent",async()=>{const value=response("CUSTOMER_ONLY",{recommendedResolutionType:"REQUEUE_CORRECTIVE_REPLY",providerGenerationPossible:true,customerVisibleSendPossible:true});value.plan!.action_type="REQUEUE_CORRECTIVE_REPLY";vi.spyOn(relationshipsApi,"approveAttentionPlan").mockResolvedValue({...value.plan!,approval_state:"APPROVED"});vi.spyOn(relationshipsApi,"executeAttentionPlan").mockResolvedValue({execution_id:"exec-2",plan_id:"plan-1",action_type:"REQUEUE_CORRECTIVE_REPLY",status:"SUCCEEDED",result:{},completed_at:"2026-09-13T12:01:00Z"});setup(value);fireEvent.click(await screen.findByRole("button",{name:"Approve Resolution"}));fireEvent.click(screen.getByRole("button",{name:"Confirm & Execute"}));expect(await screen.findByText("Corrective reply queued. No message has been sent.")).toBeInTheDocument();});
 it("limits multiple-customer work to the current target and reviews safe similar cases",async()=>{vi.spyOn(relationshipsApi,"similarAttention").mockResolvedValue({items:[{relationshipKey:"fixture-steve",attentionOccurrenceId:"occ-s",displayLabel:"Fixture Steve"}]});setup(response("MULTIPLE_CUSTOMERS"));expect(await screen.findByRole("button",{name:"Resolve This Customer"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Review Similar Cases"}));expect(await screen.findByRole("button",{name:/Fixture Steve/})).toBeInTheDocument();expect(screen.getByText(/No batch action/)).toBeInTheDocument();});
 it("never offers customer mutation for global or ambiguous results",async()=>{const view=setup(response("GLOBAL_SYSTEM"));expect(await screen.findByText("Global review required")).toBeInTheDocument();expect(screen.getByRole("link",{name:"Review Global Repair"})).toBeInTheDocument();expect(screen.queryByText("Approve Resolution")).not.toBeInTheDocument();view.unmount();setup(response("AMBIGUOUS"));expect(await screen.findByText("Manual review required")).toBeInTheDocument();expect(screen.queryByText("Approve Resolution")).not.toBeInTheDocument();});
 it("surfaces inspection failure and allows re-inspection",async()=>{vi.spyOn(relationshipsApi,"inspectAttention").mockRejectedValueOnce(new Error("Inspection unavailable")).mockResolvedValueOnce(response());render(<InspectResolveDialog target={person} occurrenceId="occ-j" onClose={vi.fn()} onResolved={vi.fn()}/>);expect(await screen.findByRole("alert")).toHaveTextContent("Inspection unavailable");fireEvent.click(screen.getByRole("button",{name:"Re-inspect"}));expect(await screen.findByText("Suggested resolution")).toBeInTheDocument();});
 it("freezes the original target even when props refresh",async()=>{let finish:(value:AttentionInspectionResponse)=>void=()=>{};vi.spyOn(relationshipsApi,"inspectAttention").mockReturnValue(new Promise(resolve=>{finish=resolve;}));const view=render(<InspectResolveDialog target={person} occurrenceId="occ-j" onClose={vi.fn()} onResolved={vi.fn()}/>);view.rerender(<InspectResolveDialog target={{...person,personKey:"fixture-servet",displayName:"Fixture Servet"}} occurrenceId="occ-new" onClose={vi.fn()} onResolved={vi.fn()}/>);finish(response());await screen.findByText("Why it was flagged");expect(relationshipsApi.inspectAttention).toHaveBeenCalledWith("fixture-j","occ-j",expect.any(String));expect(screen.getByRole("heading",{name:"Fixture J"})).toBeInTheDocument();});
 it("renders superseded authority with specific success wording",async()=>{const value=response("OBSOLETE",{recommendedResolutionType:"RESOLVE_AS_SUPERSEDED",approvalRequired:true,recommendedResolutionSummary:"The obligation was superseded."});value.plan={...response().plan!,root_cause_scope:"OBSOLETE",action_type:"RESOLVE_AS_SUPERSEDED"};vi.spyOn(relationshipsApi,"approveAttentionPlan").mockResolvedValue({...value.plan,approval_state:"APPROVED"});vi.spyOn(relationshipsApi,"executeAttentionPlan").mockResolvedValue({execution_id:"exec-3",plan_id:"plan-1",action_type:"RESOLVE_AS_SUPERSEDED",status:"SUCCEEDED",result:{},completed_at:"2026-09-13T12:01:00Z"});setup(value);fireEvent.click(await screen.findByRole("button",{name:"Resolve as Superseded"}));fireEvent.click(screen.getByRole("button",{name:"Confirm & Execute"}));expect(await screen.findByText("Attention resolved as superseded.")).toBeInTheDocument();});
 it("shows stale or expired plan errors without optimistic success",async()=>{vi.spyOn(relationshipsApi,"approveAttentionPlan").mockRejectedValue(new Error("Resolution plan expired; re-inspection required."));setup();fireEvent.click(await screen.findByRole("button",{name:"Approve Resolution"}));fireEvent.click(screen.getByRole("button",{name:"Confirm & Execute"}));expect(await screen.findByRole("alert")).toHaveTextContent("expired");expect(screen.queryByText("Attention acknowledged.")).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Re-inspect"})).toBeInTheDocument();});
 it("shows execution failure and leaves resolution unconfirmed",async()=>{vi.spyOn(relationshipsApi,"approveAttentionPlan").mockResolvedValue({...response().plan!,approval_state:"APPROVED"});vi.spyOn(relationshipsApi,"executeAttentionPlan").mockRejectedValue(new Error("RESOLUTION PLAN OUT OF DATE"));const resolved=vi.fn();setup(response(),{onResolved:resolved});fireEvent.click(await screen.findByRole("button",{name:"Approve Resolution"}));fireEvent.click(screen.getByRole("button",{name:"Confirm & Execute"}));expect(await screen.findByRole("alert")).toHaveTextContent("OUT OF DATE");expect(resolved).not.toHaveBeenCalled();});
 it("cancels only the persisted plan and closes",async()=>{vi.spyOn(relationshipsApi,"rejectAttentionPlan").mockResolvedValue({...response().plan!,approval_state:"REJECTED"});const close=vi.fn();setup(response(),{onClose:close});fireEvent.click(await screen.findByRole("button",{name:"Cancel"}));await waitFor(()=>expect(relationshipsApi.rejectAttentionPlan).toHaveBeenCalledWith("fixture-j","plan-1"));expect(close).toHaveBeenCalledOnce();});
 it("cleans up keyboard handling on unmount",async()=>{const close=vi.fn();const view=setup(response(),{onClose:close});await screen.findByText("Suggested resolution");view.unmount();fireEvent.keyDown(window,{key:"Escape"});expect(close).not.toHaveBeenCalled();});
 it("submits one logical inspection under Strict Mode",async()=>{vi.spyOn(relationshipsApi,"inspectAttention").mockResolvedValue(response());render(<StrictMode><InspectResolveDialog target={person} occurrenceId="occ-j" onClose={vi.fn()} onResolved={vi.fn()}/></StrictMode>);await screen.findByText("Suggested resolution");expect(relationshipsApi.inspectAttention).toHaveBeenCalledTimes(1);});
 it("shows authoritative similar count and split automation semantics",async()=>{const value=response("MULTIPLE_CUSTOMERS",{similarCurrentCases:[{relationshipKey:"fixture-steve",attentionOccurrenceId:"occ-s",displayLabel:"Steve Huff"},{relationshipKey:"fixture-servet",attentionOccurrenceId:"occ-a",displayLabel:"Servet Aksoy"}],affectedCurrentCustomersCount:3,avaAutoState:"ON",currentOperationState:"NO_FURTHER_AUTOMATIC_ATTEMPT",globalRepairAlreadyExists:true});setup(value);await screen.findByText("Suggested resolution");expect(screen.getByText("Ava Auto: On")).toBeInTheDocument();expect(screen.getByText("Current Operation: No Further Automatic Attempt")).toBeInTheDocument();expect(screen.getByText("Similar current cases").parentElement).toHaveTextContent("2");expect(screen.getByText("Lifecycle protection available; underlying cause requires case evidence")).toBeInTheDocument();expect(screen.queryByText("Already repaired")).not.toBeInTheDocument();});
});
