import {useEffect,useRef,useState} from "react";
import {AlertTriangle,CheckCircle2,X} from "lucide-react";
import {relationshipsApi,type AttentionExecution,type AttentionInspectionResponse,type AttentionSimilarCase,type Relationship} from "./api";
import {formatChatTime} from "./chatTime";

type Props={target:Relationship;occurrenceId:string;onClose:()=>void;onResolved:()=>void;onSelectSimilar?:(relationshipKey:string)=>void};
const label=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,char=>char.toUpperCase());
const successCopy=(action:string)=>action==="REQUEUE_CORRECTIVE_REPLY"?"Corrective reply queued. No message has been sent.":action==="RESOLVE_AS_SUPERSEDED"?"Attention resolved as superseded.":"Attention acknowledged.";
const approvalCopy=(action:string,scope:string)=>action==="RESOLVE_AS_SUPERSEDED"?"Resolve as Superseded":action==="ACKNOWLEDGE_ONLY"&&scope==="OBSOLETE"?"Acknowledge Only":scope==="MULTIPLE_CUSTOMERS"?"Resolve This Customer":"Approve Resolution";

export function InspectResolveDialog({target,occurrenceId,onClose,onResolved,onSelectSimilar}:Props){
 const frozen=useRef({key:target.personKey,occurrenceId,name:target.displayName});
 const inspectionKey=useRef(crypto.randomUUID()),inspectionInFlight=useRef(false);
 const [inspection,setInspection]=useState<AttentionInspectionResponse|null>(null),[similar,setSimilar]=useState<AttentionSimilarCase[]>([]),[loading,setLoading]=useState(true),[similarLoading,setSimilarLoading]=useState(false),[confirming,setConfirming]=useState(false),[working,setWorking]=useState(false),[execution,setExecution]=useState<AttentionExecution|null>(null),[error,setError]=useState("");
 const inspect=(fresh=false)=>{if(working||inspectionInFlight.current)return;if(fresh)inspectionKey.current=crypto.randomUUID();inspectionInFlight.current=true;setLoading(true);setError("");setInspection(null);setExecution(null);relationshipsApi.inspectAttention(frozen.current.key,frozen.current.occurrenceId,inspectionKey.current).then(setInspection).catch(reason=>setError(reason instanceof Error?reason.message:"Inspection failed.")).finally(()=>{inspectionInFlight.current=false;setLoading(false);});};
 useEffect(()=>{inspect();},[]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!working){setConfirming(false);onClose();}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[working,onClose]);
 const reviewSimilar=()=>{if(!inspection||similarLoading)return;setSimilarLoading(true);setError("");relationshipsApi.similarAttention(frozen.current.key,inspection.result.inspectionId).then(value=>setSimilar(value.items)).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to review similar cases.")).finally(()=>setSimilarLoading(false));};
 const reject=()=>{const plan=inspection?.plan;if(!plan||working)return;setWorking(true);setError("");relationshipsApi.rejectAttentionPlan(frozen.current.key,plan.plan_id).then(()=>onClose()).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to cancel this plan.")).finally(()=>setWorking(false));};
 const execute=async()=>{const plan=inspection?.plan;if(!plan||working)return;setWorking(true);setError("");try{await relationshipsApi.approveAttentionPlan(frozen.current.key,plan.plan_id);const result=await relationshipsApi.executeAttentionPlan(frozen.current.key,plan.plan_id);setExecution(result);setConfirming(false);if(result.status==="SUCCEEDED")onResolved();else if(result.status==="EXECUTING"){const current=await relationshipsApi.attentionExecution(frozen.current.key,result.execution_id);setExecution(current);if(current.status==="SUCCEEDED")onResolved();}}catch(reason){setError(reason instanceof Error?reason.message:"Resolution failed. Re-inspection is required.");setConfirming(false);}finally{setWorking(false);}};
 const result=inspection?.result,plan=inspection?.plan;
 const canExecute=Boolean(plan&&result?.approvalRequired&&["CUSTOMER_ONLY","MULTIPLE_CUSTOMERS","OBSOLETE"].includes(result.rootCauseScope));
 return <div className="attention-dialog" role="dialog" aria-modal="true" aria-labelledby="attention-dialog-title"><div className="attention-dialog-card"><header><div><small>Inspect &amp; Resolve</small><h2 id="attention-dialog-title">{frozen.current.name}</h2><span>Target held while Chat refreshes</span></div><button aria-label="Close inspection" disabled={working} onClick={onClose} type="button"><X size={18}/></button></header>
 {loading&&<div className="attention-state" role="status">Inspecting current evidence… This is read-only.</div>}
 {error&&<div className="attention-state is-error" role="alert"><strong>Unable to continue safely</strong><span>{error}</span><button disabled={working} onClick={()=>inspect(true)} type="button">Re-inspect</button></div>}
 {result&&!execution&&<div className="attention-results"><div className="attention-badges"><span>{label(result.rootCauseScope)}</span><span>Risk: {label(result.riskLevel)}</span><span>Ava Auto: {label(result.avaAutoState)}</span><span>Current Operation: {label(result.currentOperationState)}</span><time>Inspected {formatChatTime(result.inspectedAt)}</time></div>
 {(result.customerVisibleSendPossible||result.providerGenerationPossible)&&<div className="attention-warning" role="alert"><AlertTriangle size={18}/><div><strong>{result.customerVisibleSendPossible?"A customer-visible send is possible":"Provider generation is possible"}</strong><span>{result.providerGenerationPossible?"This resolution may invoke an AI provider. ":""}{result.customerVisibleSendPossible?"Approval may queue a reply for later generation and delivery.":""}</span></div></div>}
 <section><h3>Why it was flagged</h3><p>{result.whyFlagged}</p><dl><div><dt>Current impact</dt><dd>{result.currentImpact}</dd></div><div><dt>Root cause</dt><dd>{result.rootCauseSummary}</dd></div><div><dt>Global defect</dt><dd>{result.futureCustomersPotentiallyAffected?"Potentially affects future customers":result.globalRepairAlreadyExists?"Already repaired":"No global defect established"}</dd></div><div><dt>Similar current cases</dt><dd>{result.similarCurrentCases.length}</dd></div></dl><p>{result.operatorExplanation}</p></section>
 <section><h3>Suggested resolution</h3><strong>{label(result.recommendedResolutionType)}</strong><p>{result.recommendedResolutionSummary}</p>{result.exactProposedActions.length>0&&<ol>{result.exactProposedActions.map(action=><li key={action}>{action}</li>)}</ol>}<small>Risk: {label(result.riskLevel)} · Database change: {result.databaseChangeRequired?"Yes":"No"}</small></section>
 {result.inspectionWarnings.length>0&&<section className="attention-caution"><h3>Inspection caution</h3>{result.inspectionWarnings.map(warning=><p key={warning}>{warning}</p>)}</section>}
 {result.rootCauseScope==="MULTIPLE_CUSTOMERS"&&<section><h3>Similar cases</h3><button disabled={similarLoading} onClick={reviewSimilar} type="button">{similarLoading?"Loading…":"Review Similar Cases"}</button>{similar.map(item=><button className="attention-similar" key={`${item.relationshipKey}-${item.attentionOccurrenceId}`} onClick={()=>onSelectSimilar?.(item.relationshipKey)} type="button">{item.displayLabel}<span>Open customer</span></button>)}<p className="attention-note">Only this customer can be resolved here. No batch action is available.</p></section>}
 {result.rootCauseScope==="GLOBAL_SYSTEM"&&<section className="attention-caution"><h3>Global review required</h3><p>No customer or system mutation is available here.</p><a href="/developer">Review Global Repair</a></section>}
 {(result.rootCauseScope==="AMBIGUOUS"||result.cannotSafelyResolveReason)&&<section className="attention-caution"><h3>Manual review required</h3><p>{result.cannotSafelyResolveReason||"The evidence does not authorize a mutation."}</p></section>}
 <footer>{canExecute&&<button disabled={working} onClick={reject} type="button">Cancel</button>}<button onClick={onClose} disabled={working} type="button">Close</button>{canExecute&&plan&&<button className="primary" disabled={working} onClick={()=>setConfirming(true)} type="button">{approvalCopy(plan.action_type,result.rootCauseScope)}</button>}</footer></div>}
 {execution&&<div className={`attention-state ${execution.status==="SUCCEEDED"?"is-success":"is-error"}`} role="status">{execution.status==="SUCCEEDED"?<><CheckCircle2/><strong>{successCopy(execution.action_type)}</strong><button onClick={onClose} type="button">Done</button></>:<><strong>Resolution did not complete.</strong><span>No success has been assumed. Re-inspect current evidence.</span><button onClick={()=>inspect(true)} type="button">Re-inspect</button></>}</div>}
 {confirming&&plan&&<div className="attention-confirm" role="alertdialog" aria-modal="true" aria-labelledby="attention-confirm-title"><div><h3 id="attention-confirm-title">Final confirmation</h3><p>Approve and execute <strong>{label(plan.action_type)}</strong> for <strong>{frozen.current.name}</strong> only?</p>{(plan.customer_visible_send_possible||plan.provider_generation_possible)&&<p className="attention-confirm-warning">This can create provider work or a later customer-visible send. It does not claim that a message has already been sent.</p>}<footer><button disabled={working} onClick={()=>setConfirming(false)} type="button">Go Back</button><button className="primary" disabled={working} onClick={()=>void execute()} type="button">{working?"Executing…":"Confirm & Execute"}</button></footer></div></div>}</div></div>;
}
