import {fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {afterEach,expect,it,vi} from "vitest";
import {RelationshipsPage} from "./RelationshipsPage";

const person={personKey:"telegram:7:8:1",telegramUserId:1,displayName:"Stu",username:"stu",identityStatus:"UNMAPPED",buyerStatus:null,lifetimeVerifiedRevenueMinor:null,qualifyingPurchaseCount:null,latestActivityAt:"2026-09-13T20:00:00Z",latestMessagePreview:"hello",activePurchaseIntent:false,activeSalesSession:false,highValueProspect:true,marketTier:"UNCLASSIFIED"};
const intelligence={person,mappingStatus:"UNMAPPED",partial:true,operatorClassification:"HIGH_VALUE_PROSPECT",effectiveAttentionPriority:"PRIORITIZED",behavioralIntelligence:{buyingIntent:"NONE",currentSignal:"NONE",salesStage:"PROSPECT"},customerValue:{buyerStatus:"UNMAPPED_PROSPECT",valueTier:"ENGAGED_PROSPECT",attentionTier:"HIGH",lifetimeSpendMinor:null,purchaseCount:null,repeatBuyer:false,relationshipLifecycle:"PROSPECT",relationshipInvestment:"STANDARD",continuationValue:"HIGH",timeWasterRisk:"NONE",retention:"NONE"},salesPerformance:{offersPresented:0,offersPurchased:0,offersNotPurchased:0,conversionRate:null,lastOffer:null,lastPurchase:null},commercialState:{activePurchaseIntent:null,activeSalesSession:null,activeOffer:null},purchaseHistory:[],relationshipIntelligence:{location:null,timezone:null,interests:[],pets:[],music:[],preferences:[]}};
const reply=(body:unknown)=>Promise.resolve(new Response(JSON.stringify(body),{status:200,headers:{"Content-Type":"application/json"}}));
afterEach(()=>vi.restoreAllMocks());

it("assigns mutually exclusive tiers after confirmation, refreshes authority, and clears to unclassified",async()=>{
 let tier:"HIGH"|"MEDIUM"|"LOW"|"UNCLASSIFIED"="UNCLASSIFIED";
 const projection=()=>({marketTier:tier,effectiveProspectInvestment:tier==="HIGH"?"MAXIMUM":tier==="LOW"?"LOW":"HIGH",highValueProspect:true,verifiedBuyer:false,repliesUsedToday:3,dailyReplyBudget:tier==="HIGH"?"FULL":tier==="MEDIUM"?7:tier==="LOW"?2:null,budgetStatus:tier==="LOW"?"EXHAUSTED":"AVAILABLE",nextBudgetResetAt:"2026-09-14T05:00:00Z",prospectReplyLimit:null,scheduleAdvanced:tier==="HIGH",advancedOperation:null});
 const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation((input,request={})=>{const url=String(input);if(url.includes("/market-tier")){if(request.method==="PUT")tier=JSON.parse(String(request.body)).marketTier;if(request.method==="DELETE")tier="UNCLASSIFIED";return reply(projection());}if(url.includes("/intelligence"))return reply(intelligence);if(url.includes("/messages?"))return reply({person,items:[],olderCursor:null,hasMoreOlder:false});if(url.includes("/control"))return reply({mode:"AVA_AUTO",controlVersion:0,activePurchaseIntent:false,activeSalesSession:false});return reply({items:[{...person,marketTier:tier}],nextCursor:null,hasMore:false,summary:{total:1,needsAttention:0,buyers:0,prospects:1,manual:0}});});
 render(<RelationshipsPage/>);fireEvent.click(await screen.findByRole("button",{name:/Stu/}));
 const choose=async(name:string)=>{fireEvent.click(screen.getByRole("button",{name:"More conversation controls"}));const choice=screen.getByRole("menuitem",{name});await waitFor(()=>expect(choice).not.toBeDisabled());fireEvent.click(choice);};
 expect(screen.queryByTitle(/Country Tier/)).not.toBeInTheDocument();await choose("HIGH");await waitFor(()=>expect(screen.getAllByTitle("Country Tier: High").length).toBeGreaterThan(0));
 fireEvent.click(screen.getByRole("button",{name:"Open Customer Intelligence"}));let card=await screen.findByRole("region",{name:"Country Tier Intelligence"});expect(card).toHaveTextContent("FULL");fireEvent.click(screen.getByRole("button",{name:"Close Customer Intelligence"}));
 await choose("MED");await waitFor(()=>expect(screen.getAllByTitle("Country Tier: Medium").length).toBeGreaterThan(0));fireEvent.click(screen.getByRole("button",{name:"Open Customer Intelligence"}));card=await screen.findByRole("region",{name:"Country Tier Intelligence"});expect(card).toHaveTextContent("3 / 7");fireEvent.click(screen.getByRole("button",{name:"Close Customer Intelligence"}));
 await choose("LOW");await waitFor(()=>expect(screen.getAllByTitle("Country Tier: Low").length).toBeGreaterThan(0));fireEvent.click(screen.getByRole("button",{name:"Open Customer Intelligence"}));card=await screen.findByRole("region",{name:"Country Tier Intelligence"});expect(card).toHaveTextContent("EXHAUSTED");expect(card).toHaveTextContent("12:00 AM");fireEvent.click(screen.getByRole("button",{name:"Close Customer Intelligence"}));
 await choose("Unclassified");await waitFor(()=>expect(screen.queryByTitle(/Country Tier/)).not.toBeInTheDocument());fireEvent.click(screen.getByRole("button",{name:"Open Customer Intelligence"}));expect(await screen.findByRole("region",{name:"Country Tier Intelligence"})).toHaveTextContent("UNCLASSIFIED");
 expect(fetchMock.mock.calls.filter(([url])=>String(url).includes("/market-tier")).length).toBeGreaterThan(4);
});

it("orders compact lifecycle, HVP, tier and policy badges and preserves buyer authority",async()=>{
 const buyer={...person,isBuyer:true,identityStatus:"MAPPED_VERIFIED",marketTier:"LOW",displayName:"Buyer"};
 vi.spyOn(globalThis,"fetch").mockImplementation(input=>{const url=String(input);if(url.includes("/market-tier"))return reply({marketTier:"LOW",effectiveProspectInvestment:"BUYER_AUTHORITY",highValueProspect:true,verifiedBuyer:true,repliesUsedToday:2,dailyReplyBudget:2,budgetStatus:"EXHAUSTED",nextBudgetResetAt:"2026-09-14T05:00:00Z",prospectReplyLimit:"NOT_APPLICABLE"});if(url.includes("/intelligence"))return reply({...intelligence,person:buyer,mappingStatus:"VERIFIED"});if(url.includes("/messages?"))return reply({person:buyer,items:[],olderCursor:null,hasMoreOlder:false});if(url.includes("/control"))return reply({mode:"AVA_AUTO",controlVersion:0,activePurchaseIntent:false,activeSalesSession:false});return reply({items:[buyer],nextCursor:null,hasMore:false,summary:{total:1,needsAttention:0,buyers:1,prospects:0,manual:0}});});
 render(<RelationshipsPage/>);const row=(await screen.findByText("Buyer")).closest("button")!;const badges=within(row).getAllByText(/CUSTOMER|HVP|LOW/);expect(badges.map(node=>node.textContent)).toEqual(["CUSTOMER","HVP","LOW"]);expect(within(row).getByTitle("Country Tier: Low")).toHaveClass("is-low");expect(within(row).getByTitle("High Value Prospect")).not.toHaveClass("is-low");fireEvent.click(row);await screen.findByRole("button",{name:"Open Customer Intelligence"});fireEvent.click(screen.getByRole("button",{name:"Open Customer Intelligence"}));const card=await screen.findByRole("region",{name:"Country Tier Intelligence"});expect(card).toHaveTextContent("Buyer Authority");expect(card).toHaveTextContent("NOT APPLICABLE");expect(card).not.toHaveTextContent("Ordinary Replies Today");
});
