import {useEffect,useState} from "react";
import {X} from "lucide-react";
import {relationshipsApi,type OfferCard,type PreparedOffer,type RelationshipControl} from "./api";
import "./relationship-offers.css";

const money=(minor:number,currency:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency}).format(minor/100);
export function RelationshipOfferDrawer({personKey,control,onClose,onSent}:{personKey:string;control:RelationshipControl;onClose:()=>void;onSent:(message:any)=>void}){
 const [view,setView]=useState("RECOMMENDED"),[type,setType]=useState(""),[search,setSearch]=useState(""),[hidePurchased,setHidePurchased]=useState(true);
 const [items,setItems]=useState<OfferCard[]>([]),[connection,setConnection]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [review,setReview]=useState<PreparedOffer|null>(null),[text,setText]=useState(""),[sending,setSending]=useState(false),[sendKey,setSendKey]=useState<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError("");relationshipsApi.offerInventory(personKey,view,type,search,hidePurchased).then(data=>{if(active){setItems(data.items);setConnection(data.businessConnectionId)}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Unable to load offers.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[personKey,view,type,search,hidePurchased]);
 const [operationId,setOperationId]=useState<string|null>(null),[deliveryState,setDeliveryState]=useState(""),[finalPrice,setFinalPrice]=useState<string|null>(null);
 const acceptStatus=(message:any)=>{
  setDeliveryState(message.state);
  if(message.priceMinor!=null&&message.currency)setFinalPrice(money(message.priceMinor,message.currency));
  if(message.state==="CONFIRMED"&&message.telegramMessageId){setSending(false);onSent(message);onClose();}
  else if(message.state==="AMBIGUOUS"){setSending(false);setError("Delivery is uncertain. Do not resend; reconciliation is required.");}
  else if(message.state==="FAILED"){setSending(false);setError(message.error||"Offer failed before confirmed delivery. Review the operation before another attempt.");}
  else if(message.operationId){setOperationId(message.operationId);}
  else {setSending(false);setDeliveryState("AMBIGUOUS");setError("Confirmation is unavailable. Do not resend.");}
 };
 useEffect(()=>{
  if(!operationId||["CONFIRMED","FAILED","AMBIGUOUS"].includes(deliveryState))return;
  let active=true;let timer:ReturnType<typeof setTimeout>;
  const poll=()=>relationshipsApi.offerStatus(personKey,operationId).then(message=>{if(active){acceptStatus(message);timer=setTimeout(poll,1500)}}).catch(()=>{if(active){setError("Status temporarily unavailable. Do not resend.");timer=setTimeout(poll,3000)}});
  timer=setTimeout(poll,500);return()=>{active=false;clearTimeout(timer)};
 },[operationId,personKey,deliveryState]);
 const choose=(item:OfferCard)=>{if(!item.eligible)return;setError("");relationshipsApi.prepareOffer(personKey,item.offeringId,control.controlVersion,connection).then(value=>{setReview(value);setText(value.defaultMessage);setSendKey(crypto.randomUUID())}).catch(reason=>setError(reason instanceof Error?reason.message:"Offer cannot be prepared."));};
 const send=()=>{if(!review||!sendKey||!text.trim()||sending||deliveryState)return;setSending(true);setDeliveryState("PREPARING");setError("");relationshipsApi.sendOffer(personKey,{offeringId:review.offering.offeringId,expectedControlVersion:review.controlVersion,businessConnectionId:review.businessConnectionId,text:text.trim(),idempotencyKey:sendKey}).then(acceptStatus).catch(reason=>{setSending(false);setDeliveryState("AMBIGUOUS");setError((reason instanceof Error?reason.message:"Confirmation unavailable.")+" Do not resend until the operation is reconciled.")});};
 return <aside aria-label="Content and Offer" className="relationship-offer-drawer"><header><div><small>Manual selling</small><h2>{review?"Review offer":"Content / Offer"}</h2></div><button aria-label="Close Content and Offer" onClick={onClose} type="button"><X size={18}/></button></header>{review?<div className="offer-review"><img alt="" src={review.offering.thumbnailUrl}/><h3>{review.offering.title}</h3><p>{review.offering.type.replaceAll("_"," ")} · {money(review.offering.priceMinor,review.offering.currency)}</p><p>Configured base price; the final checkout price is reserved when sending.</p>{finalPrice&&<p>Final checkout price: {finalPrice}</p>}{deliveryState&&!["FAILED","AMBIGUOUS"].includes(deliveryState)&&<p role="status">{deliveryState==="PREPARING"?"Preparing offer?":"Offer queued; awaiting confirmed delivery?"}</p>}<label>Operator message<textarea disabled={Boolean(deliveryState)} aria-label="Offer message" onChange={event=>{setText(event.target.value);setSendKey(crypto.randomUUID())}} rows={4} value={text}/></label>{error&&<p role="alert">{error}</p>}<footer><button disabled={Boolean(deliveryState)} onClick={()=>setReview(null)} type="button">Back</button><button disabled={sending||Boolean(deliveryState)||!text.trim()} onClick={send} type="button">{sending?"Sending…":"Send offer"}</button></footer></div>:<div className="offer-picker"><input aria-label="Search content and offers" onChange={event=>setSearch(event.target.value)} placeholder="Search content" value={search}/><div className="offer-filters"><select aria-label="Offer type" onChange={event=>setType(event.target.value)} value={type}><option value="">All</option><option value="SINGLE_IMAGE">Singles</option><option value="BUNDLE">Bundles</option></select><select aria-label="Offer view" onChange={event=>setView(event.target.value)} value={view}><option value="RECOMMENDED">Recommended</option><option value="NEVER_OFFERED">Never Offered</option><option value="ALL_ELIGIBLE">All Eligible</option><option value="PREVIOUSLY_OFFERED">Previously Offered</option></select><label><input checked={hidePurchased} onChange={event=>setHidePurchased(event.target.checked)} type="checkbox"/> Hide purchased</label></div>{loading&&<p role="status">Loading eligible offers…</p>}{error&&<p role="alert">{error}</p>}<div className="offer-grid">{items.map(item=><button disabled={!item.eligible} key={item.offeringId} onClick={()=>choose(item)} type="button"><img alt="" src={item.thumbnailUrl}/><span><strong>{item.title}</strong><small>{item.type.replaceAll("_"," ")} · {money(item.priceMinor,item.currency)}</small><em>{item.status.replaceAll("_"," ")}</em>{item.eligibilityReason&&<small>{item.eligibilityReason}</small>}{item.ownershipEvidence==="FANVUE_HISTORY_UNKNOWN"&&<small>Purchase history unavailable before account verification.</small>}</span></button>)}</div></div>}</aside>;
}
