import {useEffect,useState} from "react";
import {X} from "lucide-react";
import {relationshipsApi,type OfferCard,type PreparedOffer,type RelationshipControl} from "./api";
import "./relationship-offers.css";

const money=(minor:number,currency:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency}).format(minor/100);
export function RelationshipOfferDrawer({personKey,control,onClose,onSent}:{personKey:string;control:RelationshipControl;onClose:()=>void;onSent:(message:any)=>void}){
 const [view,setView]=useState("RECOMMENDED"),[type,setType]=useState(""),[search,setSearch]=useState(""),[hidePurchased,setHidePurchased]=useState(true);
 const [items,setItems]=useState<OfferCard[]>([]),[connection,setConnection]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [review,setReview]=useState<PreparedOffer|null>(null),[text,setText]=useState(""),[sending,setSending]=useState(false),[sendKey,setSendKey]=useState<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError("");relationshipsApi.offerInventory(personKey,view,type,search,hidePurchased).then(data=>{if(active){setItems(data.items);setConnection(data.businessConnectionId)}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Unable to load offers.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[personKey,view,type,search,hidePurchased]);
 const choose=(item:OfferCard)=>{if(!connection||!item.eligible)return;setError("");relationshipsApi.prepareOffer(personKey,item.offeringId,control.controlVersion,connection).then(value=>{setReview(value);setText(value.defaultMessage);setSendKey(crypto.randomUUID())}).catch(reason=>setError(reason instanceof Error?reason.message:"Offer cannot be prepared."));};
 const send=()=>{if(!review||!sendKey||!text.trim()||sending)return;setSending(true);setError("");relationshipsApi.sendOffer(personKey,{offeringId:review.offering.offeringId,expectedControlVersion:review.controlVersion,businessConnectionId:review.businessConnectionId,text:text.trim(),idempotencyKey:sendKey}).then(message=>{onSent(message);onClose()}).catch(reason=>setError(reason instanceof Error?reason.message:"Offer was not sent.")).finally(()=>setSending(false));};
 return <aside aria-label="Content and Offer" className="relationship-offer-drawer"><header><div><small>Manual selling</small><h2>{review?"Review offer":"Content / Offer"}</h2></div><button aria-label="Close Content and Offer" onClick={onClose} type="button"><X size={18}/></button></header>{review?<div className="offer-review"><img alt="" src={review.offering.thumbnailUrl}/><h3>{review.offering.title}</h3><p>{review.offering.type.replaceAll("_"," ")} · {money(review.offering.priceMinor,review.offering.currency)}</p><label>Operator message<textarea aria-label="Offer message" onChange={event=>{setText(event.target.value);setSendKey(crypto.randomUUID())}} rows={4} value={text}/></label>{error&&<p role="alert">{error}</p>}<footer><button onClick={()=>setReview(null)} type="button">Back</button><button disabled={sending||!text.trim()} onClick={send} type="button">{sending?"Sending…":"Send offer"}</button></footer></div>:<div className="offer-picker"><input aria-label="Search content and offers" onChange={event=>setSearch(event.target.value)} placeholder="Search content" value={search}/><div className="offer-filters"><select aria-label="Offer type" onChange={event=>setType(event.target.value)} value={type}><option value="">All</option><option value="SINGLE_IMAGE">Singles</option><option value="BUNDLE">Bundles</option></select><select aria-label="Offer view" onChange={event=>setView(event.target.value)} value={view}><option value="RECOMMENDED">Recommended</option><option value="NEVER_OFFERED">Never Offered</option><option value="ALL_ELIGIBLE">All Eligible</option><option value="PREVIOUSLY_OFFERED">Previously Offered</option></select><label><input checked={hidePurchased} onChange={event=>setHidePurchased(event.target.checked)} type="checkbox"/> Hide purchased</label></div>{loading&&<p role="status">Loading eligible offers…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!connection&&<p>Telegram Business connection evidence is unavailable.</p>}<div className="offer-grid">{items.map(item=><button disabled={!item.eligible||!connection} key={item.offeringId} onClick={()=>choose(item)} type="button"><img alt="" src={item.thumbnailUrl}/><span><strong>{item.title}</strong><small>{item.type.replaceAll("_"," ")} · {money(item.priceMinor,item.currency)}</small><em>{item.status.replaceAll("_"," ")}</em></span></button>)}</div></div>}</aside>;
}
