"""Read-only AI pricing playground for uploaded images."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

import streamlit as st

from app.models.asset import Asset
from app.models.product import ProductType
from app.services.ai_product_drafting_service import AIProductDraftingService
from app.services.content_classification_service import (
    classify_content_image,
    determine_sexual_intensity,
)


def _coerce_list(value: Any) -> list[str]:
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            parsed = [value]
        value = parsed
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return []


def _format_price(cents: int | None) -> str:
    if cents is None:
        return "Not set"
    return f"${cents / 100:.2f}"


def _pricing_decision(asset: Asset, product_type: ProductType) -> dict:
    """
    Return the exact Phase 2E pricing decision used by autonomous activation.

    Newer code exposes ``pricing_decision_for_asset`` for rich playground debug
    output. Older/running Streamlit sessions may still have only the original
    activation method loaded, so fall back to ``_price_band_for_asset`` instead
    of duplicating pricing math here.
    """

    rich_decision = getattr(
        AIProductDraftingService,
        "pricing_decision_for_asset",
        None,
    )
    if callable(rich_decision):
        return rich_decision(asset, product_type)

    activation_price_band = AIProductDraftingService._price_band_for_asset(
        asset,
        product_type,
    )
    classification = (asset.classification or "").upper() or None
    confidence = float(asset.confidence or 0)
    return {
        "pricing_rule": f"{classification or 'UNKNOWN'}_{product_type.value}",
        **activation_price_band,
        "classification": classification,
        "product_type": product_type.value,
        "confidence": confidence,
        "tags": list(asset.suggested_tags),
        "themes": list(asset.detected_themes),
        "sexual_intensity": asset.sexual_intensity,
        "factors": [
            {
                "factor": "activation_price_band",
                "value": "AIProductDraftingService._price_band_for_asset",
                "price_delta_cents": activation_price_band.get(
                    "base_price_cents"
                ),
            }
        ],
        "explanation": (
            "Pricing generated by the Phase 2E autonomous activation price "
            "band method."
        ),
    }


def _default_product_type(file_name: str) -> ProductType:
    suffix = Path(file_name).suffix.lower()
    if suffix in {".mp4", ".mov", ".m4v", ".webm"}:
        return ProductType.SINGLE_VIDEO
    return ProductType.SINGLE_IMAGE


def _asset_from_result(
    *,
    uploaded_file_name: str,
    temp_path: Path,
    classification_result: dict,
) -> Asset:
    final_classification = classification_result.get("final_classification")
    gpt_raw = classification_result.get("gpt_vision_raw") or {}
    final_result = classification_result.get("final_classification_result") or {}
    nudenet_result = classification_result.get("nudenet") or []
    tags = _coerce_list(gpt_raw.get("suggested_tags"))
    themes = _coerce_list(gpt_raw.get("detected_themes"))

    return Asset(
        id=0,
        file_path=str(temp_path),
        file_name=uploaded_file_name,
        classification=final_classification,
        confidence=gpt_raw.get("confidence"),
        status="playground",
        is_active=True,
        is_test=True,
        ready_for_rotation=False,
        upload_intent=classification_result.get("upload_intent"),
        content_tier=None,
        distribution_type=None,
        blurred_preview_path=None,
        suggested_tags=tuple(tags),
        detected_themes=tuple(themes),
        is_explicit=final_classification == "PREMIUM",
        fanvue_media_preview_uuid=None,
        fanvue_media_full_uuid=None,
        created_at=None,
        summary=gpt_raw.get("short_safe_summary"),
        risk_flags=tuple(_coerce_list(gpt_raw.get("risk_flags"))),
        reasoning=gpt_raw.get("reasoning"),
        analysis_provenance={
            "source": "pricing_playground",
            "save_to_db": False,
            "fanvue_upload_enabled": False,
        },
        media_metadata={
            "file_name": uploaded_file_name,
            "mime_type": classification_result.get("mime_type"),
        },
        creator_profile_id=None,
        nudity_labels=tuple(_coerce_list(nudenet_result)),
        nudity_level=None,
        sexual_intensity=determine_sexual_intensity(final_classification),
        gpt_vision_result=gpt_raw,
        nudenet_result=nudenet_result,
        classification_result=final_result,
    )


def _run_read_only_analysis(uploaded_file) -> tuple[dict, Path]:
    suffix = Path(uploaded_file.name).suffix or ".jpg"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temp_file:
        temp_file.write(uploaded_file.getbuffer())
        temp_path = Path(temp_file.name)

    result = classify_content_image(
        temp_path,
        save_to_db=False,
        is_test=True,
        upload_intent="ppv_image",
        fanvue_upload_enabled=False,
    )
    return result, temp_path


def render_pricing_playground() -> None:
    st.title("Pricing Playground")
    st.caption(
        "Upload an image to test AI classification and Phase 2E pricing. "
        "This page does not write to the database, create Products, activate "
        "Products, call provider APIs, or send Telegram messages."
    )

    uploaded_file = st.file_uploader(
        "Upload Image",
        type=["jpg", "jpeg", "png", "webp"],
        accept_multiple_files=False,
    )

    if not uploaded_file:
        st.info("Upload an image to run the read-only pricing preview.")
        return

    st.image(uploaded_file, caption=uploaded_file.name, width=320)

    product_type_options = [
        ProductType.SINGLE_IMAGE,
        ProductType.PHOTO_SET,
        ProductType.VIDEO_SET,
        ProductType.SESSION,
        ProductType.STORY,
        ProductType.BUNDLE,
        ProductType.CUSTOM,
    ]
    default_type = _default_product_type(uploaded_file.name)
    selected_product_type = st.selectbox(
        "Product Type for Pricing Test",
        product_type_options,
        index=product_type_options.index(default_type),
        format_func=lambda product_type: product_type.value,
        help=(
            "This does not save anything. It only lets you preview how the "
            "same pricing logic behaves for different sellable product types."
        ),
    )

    if not st.button("Run Pricing Test", type="primary"):
        return

    temp_path = None
    with st.spinner("Running GPT Vision, classification, and pricing..."):
        try:
            classification_result, temp_path = _run_read_only_analysis(uploaded_file)
            if not classification_result.get("success"):
                st.error(classification_result.get("error") or "Analysis failed.")
                return

            asset = _asset_from_result(
                uploaded_file_name=uploaded_file.name,
                temp_path=temp_path,
                classification_result=classification_result,
            )
            pricing_decision = _pricing_decision(
                asset,
                selected_product_type,
            )
        except Exception as error:
            st.exception(error)
            return
        finally:
            if temp_path:
                try:
                    temp_path.unlink(missing_ok=True)
                except Exception:
                    pass

    st.success("Read-only pricing analysis complete.")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Classification", asset.classification or "Unknown")
    col2.metric(
        "Confidence",
        (
            f"{float(asset.confidence):.2f}"
            if asset.confidence is not None
            else "Unknown"
        ),
    )
    col3.metric("Product Type", selected_product_type.value)
    col4.metric("Pricing Rule", pricing_decision["pricing_rule"])

    st.markdown("### Tags")
    st.write(", ".join(asset.suggested_tags) or "None")

    st.markdown("### Themes")
    st.write(", ".join(asset.detected_themes) or "None")

    st.markdown("### Pricing")
    price1, price2, price3 = st.columns(3)
    price1.metric("Base Price", _format_price(pricing_decision["base_price_cents"]))
    price2.metric("Min Price", _format_price(pricing_decision["min_price_cents"]))
    price3.metric("Max Price", _format_price(pricing_decision["max_price_cents"]))

    st.markdown("### Pricing Explanation")
    st.write(pricing_decision["explanation"])
    st.write(f"Classification: `{asset.classification or 'Unknown'}`")
    st.write(f"Product Type: `{selected_product_type.value}`")
    st.write(f"Pricing Rule Applied: `{pricing_decision['pricing_rule']}`")
    st.write(
        "Range: "
        f"`{_format_price(pricing_decision['min_price_cents'])}` - "
        f"`{_format_price(pricing_decision['max_price_cents'])}`"
    )

    st.markdown("#### Pricing Factors")
    st.dataframe(
        [
            {
                "Factor": factor["factor"],
                "Value": factor["value"],
                "Delta": _format_price(factor["price_delta_cents"]),
            }
            for factor in pricing_decision["factors"]
        ],
        use_container_width=True,
        hide_index=True,
    )

    with st.expander("Debug: raw pricing decision object", expanded=False):
        st.json(pricing_decision)

    with st.expander("Debug: raw classification result", expanded=False):
        st.json(classification_result)
