import { ExternalLink, RotateCcw, Search, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { PageHeader } from "../../shared/ui/PageHeader";
import "./regenerated-content.css";

type Item={resultId:string;operationId:string;variationIndex:number;generatedImageId:string;sourceGeneratedImageId:string;providerDisplayName:string;modelDisplayName:string|null;sourceWorkflow:string|null;generatedAt:string|null;archivedAt:string|null;mediaUrl:string};
export function RegeneratedContentPage(){
 const navigate=useNavigate(); const [items,setItems]=useState<Item[]>([]); const [search,setSearch]=useState(""); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(""); const [preview,setPreview]=useState<Item|null>(null); const [version,setVersion]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);fetch(`/api/v1/regeneration/archive/items?page=${page}&search=${encodeURIComponent(search)}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{const b=await r.json() as {success:boolean;items?:Item[];totalPages?:number;error?:string};if(!r.ok||!b.success)throw new Error(b.error||"Unable to load Regenerated Content.");setItems(b.items||[]);setPages(b.totalPages||1)}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"Unable to load Regenerated Content.")}).finally(()=>setLoading(false));return()=>controller.abort()},[page,search,version]);
 const act=async(item:Item,action:"restore"|"promote")=>{setBusy(`${item.resultId}:${action}`);setError("");try{const url=action==="restore"?`/api/v1/regeneration/${item.operationId}/results/${item.resultId}/restore`:`/api/v1/regeneration/${item.operationId}/promote`;const response=await fetch(url,{method:"POST",headers:action==="promote"?{"Content-Type":"application/json"}:undefined,body:action==="promote"?JSON.stringify({result_ids:[item.resultId]}):undefined});const body=await response.json() as {success:boolean;redirect?:string;error?:string};if(!response.ok||!body.success)throw new Error(body.error||"Archive action failed.");setItems(current=>current.filter(x=>x.resultId!==item.resultId));setPreview(null);if(action==="restore")navigate(body.redirect||`/studio/regeneration?source=${item.sourceGeneratedImageId}&operation=${item.operationId}`);else setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:"Archive action failed.")}finally{setBusy("")}};
 return <section className="regenerated-content"><PageHeader title="Regenerated Content" description="Browse regenerated variations archived from Regeneration Studio."/><div className="regenerated-content__toolbar"><label><Search size={16}/><span className="sr-only">Search regenerated content</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search source, provider, or image ID"/></label></div>{loading&&<div className="regenerated-content__state">Loading Regenerated Content…</div>}{error&&<div role="alert" className="regenerated-content__state">{error}</div>}{!loading&&!items.length&&<div className="regenerated-content__state">No archived regenerated content.</div>}<div className="regenerated-content__grid">{items.map(item=><article key={item.resultId}><button className="regenerated-content__preview" onClick={()=>setPreview(item)} type="button"><img src={item.mediaUrl} alt={`Archived variation ${item.variationIndex}`}/></button><div><strong>Variation {item.variationIndex}</strong><span>{item.providerDisplayName}{item.modelDisplayName?` · ${item.modelDisplayName}`:""}</span><time>Archived {item.archivedAt?new Date(item.archivedAt).toLocaleDateString():"date unavailable"}</time><small>Source {item.sourceGeneratedImageId}</small><div><button disabled={Boolean(busy)} onClick={()=>void act(item,"restore")} type="button"><RotateCcw size={15}/> Restore to Regeneration Studio</button><button disabled={Boolean(busy)} onClick={()=>void act(item,"promote")} type="button"><ExternalLink size={15}/> Send to Generation Library</button></div></div></article>)}</div>{pages>1&&<nav><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}{preview&&<div className="regenerated-content__lightbox" role="dialog" aria-modal="true" aria-label="Archived regeneration preview" onMouseDown={e=>{if(e.target===e.currentTarget)setPreview(null)}}><button aria-label="Close preview" onClick={()=>setPreview(null)}><X/></button><img src={preview.mediaUrl} alt="Archived regenerated content preview"/></div>}</section>
}
