import { useEffect, useState, type FormEvent } from "react";
import { AlertTriangle, ChevronLeft, ChevronRight, ImageOff, Plus, X } from "lucide-react";

import { PageHeader } from "../../shared/ui/PageHeader";
import "./commerce.css";

type Offering = {
  offeringId:string; title:string; description:string|null; offeringType:string;
  heroAssetId:number; heroUrl:string; assetCount:number; priceMinor:number|null;
  currency:string; primarySalesChannel:string; status:string;
  publicationId:string|null; publicationStatus:string|null; provider:string|null;
  providerResourceStatus:string; deliveryUrl:string|null; updatedAt:string;
  lastError:string|null; telegramVaultStatus:string|null;
  telegramVaultPublishedAt:string|null; telegramVaultLastError:string|null;
};
type Inventory = { assetId:number; displayName:string; thumbnailUrl:string; mediaType:string };
const empty = { items:[] as Offering[], total:0, page:1, pageSize:20, totalPages:1 };
const labels = (value:string|null) => value ? value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(v)=>v.toUpperCase()) : "Not created";

export function CommercePage() {
  const [data,setData]=useState(empty); const [summary,setSummary]=useState({total:0,draft:0,ready:0,live:0,archived:0});
  const [page,setPage]=useState(1); const [searchInput,setSearchInput]=useState(""); const [search,setSearch]=useState("");
  const [status,setStatus]=useState(""); const [type,setType]=useState(""); const [publication,setPublication]=useState("");
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [refresh,setRefresh]=useState(0);
  const [wizard,setWizard]=useState(false); const [step,setStep]=useState(1); const [inventory,setInventory]=useState<Inventory[]>([]);
  const [selected,setSelected]=useState<number[]>([]); const [offeringType,setOfferingType]=useState("SINGLE_IMAGE");
  const [primarySalesChannel,setPrimarySalesChannel]=useState("AI_CHAT");
  const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [price,setPrice]=useState("");
  const [saving,setSaving]=useState(false); const [detail,setDetail]=useState<Offering|null>(null); const [editing,setEditing]=useState(false);
  const [marketingText,setMarketingText]=useState(""); const [vaultPublishing,setVaultPublishing]=useState(false);

  useEffect(()=>{ const controller=new AbortController(); const query=new URLSearchParams({page:String(page),page_size:"20"});
    if(search)query.set("search",search); if(status)query.set("status",status); if(type)query.set("offering_type",type); if(publication)query.set("publication_status",publication);
    setLoading(true); setError("");
    Promise.all([
      fetch(`/api/v1/commerce-authoring?${query}`,{cache:"no-store",signal:controller.signal}),
      fetch("/api/v1/commerce-authoring/summary",{cache:"no-store",signal:controller.signal}),
    ]).then(async([list,counts])=>{const listBody=await list.json();const countBody=await counts.json();if(!list.ok)throw new Error(listBody.detail?.message||listBody.detail||"Unable to load Commerce.");if(!counts.ok)throw new Error("Unable to load Commerce summary.");setData(listBody);setSummary(countBody);})
      .catch((reason:unknown)=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Unable to load Commerce.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();
  },[page,publication,refresh,search,status,type]);
  const openWizard=async()=>{setWizard(true);setStep(1);setSelected([]);setPrimarySalesChannel("AI_CHAT");setError("");const response=await fetch("/api/v1/available-inventory?page=1&page_size=100&sort=newest",{cache:"no-store"});const body=await response.json();if(response.ok)setInventory(body.items||[]);else setError(body.detail||"Unable to load Available Inventory.");};
  const compatible=inventory.filter((item)=>offeringType==="VIDEO"?item.mediaType==="video":item.mediaType==="image");
  const validSelection=offeringType==="PHOTOSET"?selected.length>=2:selected.length===1;
  const create=async()=>{setSaving(true);setError("");try{const response=await fetch("/api/v1/commerce-authoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({offeringType,title,description:description||null,heroAssetId:selected[0],primarySalesChannel,assetIds:selected,priceMinor:Math.round(Number(price)*100),currency:"USD"})});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail||"Unable to create offering.");setWizard(false);setRefresh((v)=>v+1);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create offering.");}finally{setSaving(false);}};
  const edit=async()=>{if(!detail)return;setSaving(true);try{const response=await fetch(`/api/v1/commerce-authoring/${detail.offeringId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({title,description:description||null,priceMinor:Math.round(Number(price)*100),currency:"USD"})});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail);setDetail({...detail,...body});setEditing(false);setRefresh((v)=>v+1);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to edit offering.");}finally{setSaving(false);}};
  const act=async(item:Offering,action:"publish"|"archive")=>{if(action==="archive"&&!window.confirm(`Archive ${item.title}?`))return;setError("");const response=await fetch(`/api/v1/commerce-authoring/${item.offeringId}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const body=await response.json();if(!response.ok){setError(body.detail?.message||body.detail||`Unable to ${action}.`);return;}setRefresh((v)=>v+1);setDetail(null);};
  const openDetail=(item:Offering)=>{setDetail(item);setTitle(item.title);setDescription(item.description||"");setPrice(item.priceMinor==null?"":(item.priceMinor/100).toFixed(2));setEditing(false);};
  const publishVault=async()=>{if(!detail)return;setVaultPublishing(true);setError("");try{const response=await fetch(`/api/v1/commerce-authoring/${detail.offeringId}/telegram-content-vault`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({marketingText:marketingText.trim()||null})});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail||"Unable to publish to Telegram Content Vault.");setDetail({...detail,telegramVaultStatus:"PUBLISHED",telegramVaultPublishedAt:body.publishedAt,telegramVaultLastError:null});setRefresh((v)=>v+1);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to publish to Telegram Content Vault.");}finally{setVaultPublishing(false);}};
  return <section className="commerce-page"><PageHeader title="Commerce" description="Author and publish the AI Chat catalog from Available Inventory." />
    <div className="commerce-summary">{Object.entries(summary).map(([key,value])=><article key={key}><span>{labels(key)}</span><strong>{value}</strong></article>)}</div>
    <div className="commerce-toolbar"><form onSubmit={(event:FormEvent)=>{event.preventDefault();setSearch(searchInput.trim());setPage(1);}}><input aria-label="Search Commerce" placeholder="Search offerings" value={searchInput} onChange={(e)=>setSearchInput(e.target.value)}/><button>Search</button></form><select aria-label="Offering status" value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option><option>DRAFT</option><option>READY</option><option>ARCHIVED</option></select><select aria-label="Offering type filter" value={type} onChange={(e)=>{setType(e.target.value);setPage(1);}}><option value="">All types</option><option>SINGLE_IMAGE</option><option>PHOTOSET</option><option>VIDEO</option></select><select aria-label="Publication status" value={publication} onChange={(e)=>{setPublication(e.target.value);setPage(1);}}><option value="">All publication states</option><option>READY_TO_PUBLISH</option><option>PUBLISHING</option><option>LIVE</option><option>FAILED</option><option>ARCHIVED</option></select><button className="commerce-new" onClick={()=>void openWizard()}><Plus size={16}/>New Offering</button></div>
    {error&&<div className="commerce-state commerce-error" role="alert"><AlertTriangle/>{error}</div>}{loading&&<div className="commerce-state">Loading Commerce…</div>}
    {!loading&&!error&&!data.items.length&&<div className="commerce-state"><strong>No offerings found.</strong><span>Create one from Available Inventory.</span></div>}
    {!loading&&data.items.length>0&&<div className="commerce-grid">{data.items.map((item)=><article key={item.offeringId}><button className="commerce-hero" aria-label={`View ${item.title}`} onClick={()=>openDetail(item)}>{item.heroUrl?<img alt="" loading="lazy" src={item.heroUrl}/>:<ImageOff/>}</button><div><small>{labels(item.offeringType)}</small><h2>{item.title}</h2><p>{item.description}</p><dl><div><dt>Assets</dt><dd>{item.assetCount}</dd></div><div><dt>Price</dt><dd>{item.priceMinor==null?"Not set":`$${(item.priceMinor/100).toFixed(2)}`}</dd></div><div><dt>Channel</dt><dd>{labels(item.primarySalesChannel)}</dd></div><div><dt>Offering</dt><dd>{labels(item.status)}</dd></div><div><dt>Publication</dt><dd>{labels(item.publicationStatus)}</dd></div><div><dt>Provider</dt><dd>{labels(item.providerResourceStatus)}</dd></div><div><dt>Content Vault</dt><dd>{labels(item.telegramVaultStatus)}</dd></div></dl><div className="commerce-actions"><button onClick={()=>openDetail(item)}>View</button><button disabled={item.publicationStatus==="PUBLISHING"} onClick={()=>openDetail(item)}>Edit</button><button disabled={["LIVE","PUBLISHING","ARCHIVED"].includes(item.publicationStatus||"")||item.status==="ARCHIVED"} title={item.status==="ARCHIVED"?"Archived offerings cannot publish":undefined} onClick={()=>void act(item,"publish")}>Publish</button><button disabled={item.status==="ARCHIVED"||item.publicationStatus==="PUBLISHING"} onClick={()=>void act(item,"archive")}>Archive</button></div></div></article>)}</div>}
    {data.totalPages>1&&<nav className="commerce-pagination"><button disabled={page<=1} onClick={()=>setPage((v)=>v-1)}><ChevronLeft/>Previous</button><span>Page {data.page} of {data.totalPages}</span><button disabled={page>=data.totalPages} onClick={()=>setPage((v)=>v+1)}>Next<ChevronRight/></button></nav>}
    {wizard&&<div className="commerce-dialog" role="dialog" aria-modal="true" aria-label="New Offering"><div><header><div><small>Step {step} of 5</small><h2>New Offering</h2></div><button aria-label="Close New Offering" onClick={()=>setWizard(false)}><X/></button></header>
      {step===1&&<><h3>Select Available Inventory</h3><p>{selected.length} selected</p><div className="commerce-inventory">{compatible.map((item)=><label key={item.assetId}><img alt="" src={item.thumbnailUrl}/><input checked={selected.includes(item.assetId)} onChange={()=>setSelected((current)=>current.includes(item.assetId)?current.filter((id)=>id!==item.assetId):[...current,item.assetId])} type="checkbox"/><span>{item.displayName}</span></label>)}</div></>}
      {step===2&&<><h3>Offering Type</h3><select aria-label="New offering type" value={offeringType} onChange={(e)=>{setOfferingType(e.target.value);setSelected([]);}}><option value="SINGLE_IMAGE">Single Image</option><option value="PHOTOSET">Photoset</option><option value="VIDEO">Video</option><option disabled>Story — Coming Soon</option><option disabled>Story Set — Coming Soon</option><option disabled>Bundle — Coming Soon</option></select></>}
      {step===3&&<><h3>Metadata and Pricing</h3><label>Title<input aria-label="Commerce title" maxLength={200} value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label>Description<textarea aria-label="Commerce description" maxLength={2000} value={description} onChange={(e)=>setDescription(e.target.value)}/></label><label>Price (USD)<input aria-label="Commerce price" min="3" max="500" step=".01" type="number" value={price} onChange={(e)=>setPrice(e.target.value)}/></label></>}
      {step===4&&<><h3>Primary Sales Channel</h3><label><input checked={primarySalesChannel==="AI_CHAT"} name="primary-channel" onChange={()=>setPrimarySalesChannel("AI_CHAT")} type="radio"/>AI Chat</label><label><input checked={primarySalesChannel==="TELEGRAM_WALL"} name="primary-channel" onChange={()=>setPrimarySalesChannel("TELEGRAM_WALL")} type="radio"/>Telegram Content Vault</label></>}
      {step===5&&<><h3>Review</h3><dl><div><dt>Type</dt><dd>{labels(offeringType)}</dd></div><div><dt>Assets</dt><dd>{selected.length}</dd></div><div><dt>Cover</dt><dd>Asset #{selected[0]}</dd></div><div><dt>Title</dt><dd>{title}</dd></div><div><dt>Description</dt><dd>{description||"None"}</dd></div><div><dt>Price</dt><dd>${Number(price||0).toFixed(2)} USD</dd></div><div><dt>Channel</dt><dd>{primarySalesChannel==="TELEGRAM_WALL"?"Telegram Content Vault":"AI Chat"}</dd></div></dl></>}
      <footer><button disabled={step===1} onClick={()=>setStep((v)=>v-1)}>Back</button>{step<5?<button disabled={(step===1&&!selected.length)||(step===3&&(!title.trim()||Number(price)<3))||(step===2&&!validSelection)} onClick={()=>setStep((v)=>v+1)}>Next</button>:<button disabled={saving||!validSelection} onClick={()=>void create()}>{saving?"Creating…":"Create Offering"}</button>}</footer></div></div>}
    {detail&&<div className="commerce-dialog" role="dialog" aria-modal="true" aria-label={`${detail.title} details`}><div><header><h2>{detail.title}</h2><button aria-label="Close details" onClick={()=>setDetail(null)}><X/></button></header><img className="commerce-detail-image" alt="" src={detail.heroUrl}/>{editing?<><label>Title<input aria-label="Edit title" value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label>Description<textarea aria-label="Edit description" value={description} onChange={(e)=>setDescription(e.target.value)}/></label><label>Price (USD)<input aria-label="Edit price" type="number" step=".01" value={price} onChange={(e)=>setPrice(e.target.value)}/></label><button disabled={saving} onClick={()=>void edit()}>Save Changes</button></>:<><p>{detail.description}</p><dl><div><dt>Type</dt><dd>{labels(detail.offeringType)}</dd></div><div><dt>Assets</dt><dd>{detail.assetCount}</dd></div><div><dt>Publication</dt><dd>{labels(detail.publicationStatus)}</dd></div><div><dt>Provider resource</dt><dd>{labels(detail.providerResourceStatus)}</dd></div><div><dt>Delivery</dt><dd>{detail.deliveryUrl?<a href={detail.deliveryUrl} target="_blank" rel="noreferrer">Active delivery URL</a>:"Not ready"}</dd></div><div><dt>Content Vault</dt><dd>{labels(detail.telegramVaultStatus)}</dd></div><div><dt>Last error</dt><dd>{detail.telegramVaultLastError||detail.lastError||"None"}</dd></div></dl><button disabled={detail.publicationStatus==="PUBLISHING"} onClick={()=>setEditing(true)}>Edit</button><label>Optional marketing text<textarea aria-label="Telegram Content Vault marketing text" maxLength={500} value={marketingText} onChange={(event)=>setMarketingText(event.target.value)}/></label><button disabled={vaultPublishing||detail.telegramVaultStatus==="PUBLISHED"||detail.status==="ARCHIVED"||!detail.deliveryUrl} title={!detail.deliveryUrl?"An active Fanvue Media Link is required":undefined} onClick={()=>void publishVault()}>{vaultPublishing?"Publishing…":"Publish to Telegram Content Vault"}</button></>}</div></div>}
  </section>;
}
