import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ChevronLeft, ChevronRight, Search, X } from "lucide-react";
import { Link } from "react-router-dom";

import { PageHeader } from "../../shared/ui/PageHeader";
import { salesApi } from "./api";
import type { Page, SalesDecision, SalesLearning, SalesOffer, SalesOverview } from "./types";
import "./business-sales.css";

type Tab = "dashboard" | "activity" | "offers" | "learning";
const emptyPage = <T,>(): Page<T> => ({ items: [], total: 0, page: 1, pageSize: 24, totalPages: 1 });
const title = (value: unknown) => String(value ?? "Unknown").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const money = (cents: unknown) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(cents || 0) / 100);
const when = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "Unknown time";

function Warning({ children }: { children: React.ReactNode }) { return <div className="sales-warning"><AlertTriangle size={15} />{children}</div>; }
function MetricGrid({ values }: { values: Array<[string, unknown, ("money" | "percent")?]> }) { return <div className="sales-metrics">{values.map(([label, value, kind]) => <article key={label}><span>{label}</span><strong>{kind === "money" ? money(value) : kind === "percent" ? `${(Number(value || 0) * 100).toFixed(1)}%` : String(value ?? 0)}</strong></article>)}</div>; }
function ReadSection({ heading, data }: { heading: string; data: Record<string, unknown> | undefined }) { const entries = Object.entries(data || {}).filter(([key]) => !key.toLowerCase().includes("raw")).slice(0, 16); return <section className="sales-detail__section"><h3>{heading}</h3>{entries.length ? <dl>{entries.map(([key, value]) => <div key={key}><dt>{title(key)}</dt><dd>{typeof value === "object" ? JSON.stringify(value) : typeof value === "boolean" ? (value ? "Yes" : "No") : String(value ?? "Not recorded")}</dd></div>)}</dl> : <p>Not correlated.</p>}</section>; }

export function BusinessSalesPage() {
  const [tab, setTab] = useState<Tab>("dashboard"); const [overview, setOverview] = useState<SalesOverview | null>(null); const [activity, setActivity] = useState<Page<SalesDecision>>(emptyPage); const [offers, setOffers] = useState<Page<SalesOffer>>(emptyPage); const [learning, setLearning] = useState<SalesLearning | null>(null);
  const [search, setSearch] = useState(""); const [sell, setSell] = useState(""); const [authorization, setAuthorization] = useState(""); const [outcome, setOutcome] = useState(""); const [page, setPage] = useState(1); const [offerState, setOfferState] = useState(""); const [offerPage, setOfferPage] = useState(1);
  const [selected, setSelected] = useState<SalesDecision | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");

  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); const params = new URLSearchParams({ page: String(page), page_size: "24" }); if (search.trim()) params.set("search", search.trim()); if (sell) params.set("sell", sell); if (authorization) params.set("authorized", authorization); if (outcome) params.set("outcome", outcome); const offerParams = new URLSearchParams({ page: String(offerPage), page_size: "24" }); if (search.trim()) offerParams.set("search", search.trim()); if (offerState) offerParams.set("state", offerState); const request = tab === "dashboard" ? salesApi.overview(controller.signal).then(setOverview) : tab === "activity" ? salesApi.decisions(params, controller.signal).then(setActivity) : tab === "offers" ? salesApi.offers(offerParams, controller.signal).then(setOffers) : salesApi.learning(controller.signal).then(setLearning); request.catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Unable to load Sales workspace."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [tab, search, sell, authorization, outcome, page, offerState, offerPage]);

  const openDecision = useCallback(async (decision: SalesDecision) => { setError(""); try { setSelected(await salesApi.decision(decision.decisionId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load Decision Activity."); } }, []);
  const tabs: Array<[Tab, string]> = [["dashboard", "Dashboard"], ["activity", "Activity"], ["offers", "Offers"], ["learning", "Learning"]];
  return <section className="business-sales-page"><PageHeader title="Sales" description="Observe what the Sales Agent decided and what persisted outcomes followed." />
    <nav className="sales-tabs" aria-label="Sales workspace tabs">{tabs.map(([value, label]) => <button aria-selected={tab === value} className={tab === value ? "is-active" : ""} key={value} onClick={() => setTab(value)} role="tab">{label}</button>)}</nav>
    {error && <div className="sales-state sales-state--error" role="alert"><AlertTriangle size={18} />{error}</div>}{loading && <div className="sales-state">Loading Sales observability…</div>}
    {!loading && tab === "dashboard" && overview && <div className="sales-panel"><MetricGrid values={[["Decision Activities Today", overview.metrics.decisionActivitiesToday], ["Sell Decisions", overview.metrics.sellDecisions], ["No-Sell Decisions", overview.metrics.noSellDecisions], ["Offers Authorized", overview.metrics.offersAuthorized], ["Purchases", overview.metrics.purchases], ["Revenue", overview.metrics.revenueCents, "money"], ["Conversion", overview.metrics.conversionRate, "percent"], ["Blocked / Suppressed", overview.metrics.blockedOrSuppressed], ["Delivery Failures", overview.metrics.deliveryFailures], ["Active Buyer Sessions", overview.metrics.activeBuyerSessions], ["Learning Issues", overview.metrics.learningIssues]]} />{overview.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<div className="sales-dashboard-grid"><section><h2>Recent Decision Activity</h2>{overview.recentActivity.length ? overview.recentActivity.map((item) => <button className="sales-mini-row" key={item.decisionId} onClick={() => void openDecision(item)}><span>{when(item.timestamp)} · {item.customerName}</span><strong>{item.sellDecision ? "Sell" : "No sell"} · {title(item.route)}</strong></button>) : <p>No persisted Decision Activity.</p>}</section><section><h2>Learning Attention</h2><p>Unmatched outcomes: {overview.unmatchedOutcomes.length}</p><p>High-priority recommendations: {overview.highPriorityRecommendations.length}</p>{overview.learningWarnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}</section></div></div>}
    {!loading && tab === "activity" && <div className="sales-panel"><div className="sales-toolbar"><label className="sales-search"><Search size={16} /><input aria-label="Search Decision Activity" placeholder="Search customer, message, product, or asset" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></label><label>Decision<select aria-label="Sell decision" value={sell} onChange={(event) => { setSell(event.target.value); setPage(1); }}><option value="">All</option><option value="true">Sell</option><option value="false">No sell</option></select></label><label>Authorization<select aria-label="Authorization" value={authorization} onChange={(event) => { setAuthorization(event.target.value); setPage(1); }}><option value="">All</option><option value="authorized">Authorized</option><option value="blocked">Blocked</option><option value="unknown">Unknown</option></select></label><label>Outcome<select aria-label="Outcome" value={outcome} onChange={(event) => { setOutcome(event.target.value); setPage(1); }}><option value="">All</option><option value="purchased">Purchased</option><option value="refunded">Refunded</option><option value="none_confirmed">None confirmed</option></select></label></div>{!activity.items.length ? <div className="sales-state">No Decision Activity found.</div> : <div className="sales-list">{activity.items.map((item) => <button className="sales-row" key={item.decisionId} onClick={() => void openDecision(item)}><div><small>Decision Activity</small><strong>{item.customerName}</strong><span>{when(item.timestamp)}</span></div><div><small>Intent / Route</small><strong>{title(item.intent)} · {title(item.route)}</strong><span>{title(item.relationshipStage)} · {title(item.buyerTier)}</span></div><div><small>Decision</small><strong>{item.sellDecision ? "Sell" : "No sell"}</strong><span>{title(item.authorizationState)}</span></div><div><small>Offer</small><strong>{item.productId || item.assetId || "No selection"}</strong><span>{item.price === null ? "No price" : `$${item.price}`}</span></div><div><small>Confirmed state</small><strong>{title(item.deliveryState)}</strong><span>{title(item.outcomeState)}</span></div><div className={item.dataStatus === "partial" ? "needs-attention" : ""}><small>Reason</small><span>{item.reason}</span></div></button>)}</div>}<Pagination page={activity.page} total={activity.totalPages} setPage={setPage} /></div>}
    {!loading && tab === "offers" && <div className="sales-panel"><div className="sales-toolbar sales-toolbar--offers"><label className="sales-search"><Search size={16} /><input aria-label="Search Offers" placeholder="Search recommendation, customer, product, or asset" value={search} onChange={(event) => { setSearch(event.target.value); setOfferPage(1); }} /></label><label>State<select aria-label="Offer state" value={offerState} onChange={(event) => { setOfferState(event.target.value); setOfferPage(1); }}><option value="">All states</option><option value="OFFERED">Offered</option><option value="PRESENTED">Presented</option><option value="DELIVERED">Delivered</option><option value="PURCHASED">Purchased</option><option value="REFUNDED">Refunded</option><option value="DECLINED">Declined</option><option value="EXPIRED">Expired</option></select></label></div>{!offers.items.length ? <div className="sales-state">No correlated offer lifecycle found.</div> : <div className="sales-list">{offers.items.map((item) => <article className="sales-row sales-offer-row" key={item.offerId}><div><small>Offer</small><strong>{item.offerId}</strong><span>{when(item.generatedAt)}</span></div><div><small>Customer</small><strong>{item.customerId || "Not correlated"}</strong><span>{item.productId || `Asset ${item.assetId ?? "unknown"}`}</span></div><div><small>Lifecycle</small><strong>{title(item.state)}</strong><span>{item.states.join(" → ")}</span></div><div><small>Delivery</small><strong>{title(item.deliveryState)}</strong><span>{item.attributionState}</span></div><div><small>Outcome</small><strong>{item.refunded ? "Refunded" : item.purchased ? "Purchased" : "Not confirmed"}</strong><span>{money(item.revenueCents)}</span></div>{item.warnings.length ? <Warning>{item.warnings.join(" ")}</Warning> : <span />}</article>)}</div>}<Pagination page={offers.page} total={offers.totalPages} setPage={setOfferPage} /></div>}
    {!loading && tab === "learning" && learning && <div className="sales-panel"><MetricGrid values={[["Recommendations", learning.summary.recommendations], ["Offers", learning.summary.offers], ["Deliveries", learning.summary.deliveries], ["Purchases", learning.summary.purchases], ["Refunds", learning.summary.refunds], ["Net Revenue", learning.summary.netRevenueCents, "money"], ["Conversion", learning.summary.conversionRate, "percent"]]} />{learning.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<div className="sales-learning-grid"><LearningList title="Top-performing Assets" items={learning.topAssets} /><LearningList title="Underperforming Assets" items={learning.underperformingAssets} /><LearningList title="Learning Insights" items={learning.learningInsights} /><LearningList title="Existing Recommendations" items={learning.learningRecommendations} /><LearningList title="Delivery Failures" items={learning.deliveryFailures} /><LearningList title="Unmatched Outcomes" items={learning.unmatchedOutcomes} /><LearningList title="Failed Learning Events" items={learning.failedLearningEvents} /><section><h2>Suppression / Rejection</h2><p>{Object.entries(learning.suppressionReasons).map(([key, count]) => `${title(key)}: ${count}`).join(" · ") || "No suppression evidence."}</p><p>{Object.entries(learning.rejectionReasons).map(([key, count]) => `${title(key)}: ${count}`).join(" · ") || "No rejection evidence."}</p></section></div></div>}
    {selected && <aside className="sales-detail" aria-label="Decision Activity details"><header><div><small>Decision Activity</small><h2>{selected.decisionId}</h2></div><button aria-label="Close Decision Activity details" onClick={() => setSelected(null)}><X /></button></header><div className="sales-detail__body">{selected.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<section className="sales-detail__links"><Link to={`/business/customers?customer=${encodeURIComponent(selected.customerId)}`}>Business Customer</Link>{selected.productId && <Link to={`/business/products?product=${encodeURIComponent(selected.productId)}`}>Business Product</Link>}{selected.assetId && <Link to={`/business/assets?asset=${encodeURIComponent(selected.assetId)}`}>Business Asset</Link>}</section><ReadSection heading="Customer" data={selected.customerContext} /><ReadSection heading="Message and Response" data={selected.conversation} /><ReadSection heading="Classification and Routing" data={selected.classificationAndRouting} /><ReadSection heading="Sell / No-Sell Rationale" data={(selected as unknown as { sellDecision: Record<string, unknown> }).sellDecision} /><ReadSection heading="Recommendation, Product and Asset" data={selected.recommendation} /><ReadSection heading="Delivery" data={selected.delivery} /><ReadSection heading="Outcome and Learning" data={selected.outcomeAndLearning} /><section className="sales-detail__section"><h3>Warnings and Data Completeness</h3><p>Status: {title(selected.dataStatus)}</p><p>Partial sections: {selected.partialSections.join(", ") || "None"}</p></section></div></aside>}
  </section>;
}

function Pagination({ page, total, setPage }: { page: number; total: number; setPage: React.Dispatch<React.SetStateAction<number>> }) { return total > 1 ? <nav className="sales-pagination"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={15} />Previous</button><span>Page {page} of {total}</span><button disabled={page >= total} onClick={() => setPage((value) => value + 1)}>Next<ChevronRight size={15} /></button></nav> : null; }
function LearningList({ title: heading, items }: { title: string; items: Array<Record<string, unknown>> }) { return <section><h2>{heading}</h2>{items.length ? items.slice(0, 8).map((item, index) => <p key={String(item.asset_id || item.insight_id || item.recommendation_id || index)}>{Object.entries(item).filter(([, value]) => typeof value !== "object").slice(0, 4).map(([key, value]) => `${title(key)}: ${String(value)}`).join(" · ")}</p>) : <p>No persisted records.</p>}</section>; }
