import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BusinessSalesPage } from "./BusinessSalesPage";

const decision = { decisionId: "decision-1", timestamp: "2026-07-19T12:00:00Z", activityLabel: "Decision Activity", customerId: "7:42", customerName: "Avery", provider: "fanvue", messageSummary: "buy it", replySummary: "Here you go", intent: "high", route: "sales", relationshipStage: "subscriber", buyerTier: "warm", sellDecision: true, productId: "product-1", assetId: "101", offerType: "vip", price: 25, authorizationState: "unknown", reason: "Buying intent", deliveryState: "not_confirmed", outcomeState: "none_confirmed", revenueCents: 0, dataStatus: "partial", partialSections: ["delivery"], warnings: ["Decision Activity is not confirmation of an external send."], customerContext: { relationship_stage: "engaged" }, classificationAndRouting: { route: "sales" }, conversation: { customer_message: "buy it", generated_reply: "Here you go" }, recommendation: { product_id: "product-1", asset_id: 101 }, delivery: { execution_state: "not_confirmed" }, outcomeAndLearning: { learning_status: "not_correlated" } };
const overview = { metrics: { decisionActivitiesToday: 1, sellDecisions: 1, noSellDecisions: 0, offersAuthorized: 0, purchases: 0, revenueCents: 0, conversionRate: 0, blockedOrSuppressed: 0, deliveryFailures: 0, activeBuyerSessions: 1, learningIssues: 1 }, recentActivity: [decision], topAssets: [], underperformingAssets: [], highPriorityRecommendations: [], learningWarnings: [], unmatchedOutcomes: [], dataStatus: "partial", partialSections: ["externalSendConfirmation"], warnings: ["Decision Activity does not prove an external provider send occurred."] };
const offers = { items: [{ offerId: "rec-1", decisionId: null, customerId: "7:42", productId: "product-1", assetId: 101, offerType: "vip", price: 2500, generatedAt: "2026-07-19T12:00:00Z", presentedAt: null, state: "PURCHASED", states: ["OFFERED", "PURCHASED"], deliveryState: "not_confirmed", purchased: true, refunded: false, revenueCents: 2500, attributionState: "direct", attention: false, warnings: [], dataStatus: "complete" }], total: 1, page: 1, pageSize: 24, totalPages: 1 };
const learning = { summary: { recommendations: 1, offers: 1, deliveries: 0, purchases: 1, refunds: 0, netRevenueCents: 2500, conversionRate: 1 }, topAssets: [{ asset_id: 101, score: .9 }], underperformingAssets: [], topProducts: [], suppressionReasons: {}, rejectionReasons: {}, deliveryFailures: [], unmatchedOutcomes: [], failedLearningEvents: [], learningInsights: [], learningRecommendations: [], warnings: ["Partial learning data."], dataStatus: "partial" };
const response = (body: unknown, ok = true) => Promise.resolve({ ok, json: () => Promise.resolve(body) } as Response);
const renderPage = () => render(<MemoryRouter><BusinessSalesPage /></MemoryRouter>);

afterEach(() => vi.restoreAllMocks());
describe("BusinessSalesPage", () => {
  it("renders dashboard metrics and honest partial-data wording", async () => { vi.spyOn(globalThis, "fetch").mockImplementation(() => response(overview)); renderPage(); expect(await screen.findByText("Decision Activities Today")).toBeInTheDocument(); expect(screen.getByText(/does not prove an external provider send/i)).toBeInTheDocument(); expect(screen.queryByText(/^Sent$/)).not.toBeInTheDocument(); });
  it("navigates tabs, filters activity, and opens the read-only drawer", async () => { const fetch = vi.spyOn(globalThis, "fetch").mockImplementation((input) => String(input).includes("decision-1") ? response(decision) : String(input).includes("/decisions") ? response({ items: [decision], total: 1, page: 1, pageSize: 24, totalPages: 1 }) : response(overview)); renderPage(); await screen.findByText("Decision Activities Today"); fireEvent.click(screen.getByRole("tab", { name: "Activity" })); expect(await screen.findByText("Avery")).toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Search Decision Activity"), { target: { value: "avery" } }); fireEvent.change(await screen.findByLabelText("Sell decision"), { target: { value: "true" } }); await waitFor(() => expect(fetch.mock.calls.some(([url]) => String(url).includes("search=avery") && String(url).includes("sell=true"))).toBe(true)); fireEvent.click(await screen.findByText("Avery")); expect(await screen.findByRole("complementary", { name: "Decision Activity details" })).toBeInTheDocument(); expect(screen.getByText("Warnings and Data Completeness")).toBeInTheDocument(); for (const action of ["Send", "Create Offer", "Fulfill", "Retry", "Edit"]) expect(screen.queryByRole("button", { name: action })).not.toBeInTheDocument(); });
  it("renders offers and learning tabs", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => String(input).includes("/offers") ? response(offers) : String(input).includes("/learning") ? response(learning) : response(overview)); renderPage(); await screen.findByText("Decision Activities Today"); fireEvent.click(screen.getByRole("tab", { name: "Offers" })); expect(await screen.findByText("rec-1")).toBeInTheDocument(); fireEvent.click(screen.getByRole("tab", { name: "Learning" })); expect(await screen.findByText("Top-performing Assets")).toBeInTheDocument(); expect(screen.getByText("Partial learning data.")).toBeInTheDocument(); });
  it("renders empty and error states", async () => { const fetch = vi.spyOn(globalThis, "fetch").mockImplementation((input) => String(input).includes("/decisions") ? response({ items: [], total: 0, page: 1, pageSize: 24, totalPages: 1 }) : response(overview)); const view = renderPage(); await screen.findByText("Decision Activities Today"); fireEvent.click(screen.getByRole("tab", { name: "Activity" })); expect(await screen.findByText("No Decision Activity found.")).toBeInTheDocument(); view.unmount(); fetch.mockImplementation(() => response({ detail: "Sales read failed." }, false)); renderPage(); expect(await screen.findByRole("alert")).toHaveTextContent("Sales read failed."); });
});
