import { fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BusinessOperationsPage } from "./BusinessOperationsPage";
import type { OperationsWorkers } from "./types";

const overview = { overallHealth: "warning", healthScore: 91, database: { status: "healthy", summary: "Connected" }, runtimeMode: "observe", autonomousExecution: "BLOCKED", globalAutomation: true, globalSends: false, manualPause: false, queueTotals: { pending: 2 }, failureCount: 1, publishingAttention: 1, providerWarnings: [{ name: "Telegram", status: "warning", summary: "Authentication Required" }], workerCounts: { healthy: 1, stale: 1, failed: 0, untracked: 2 }, warnings: ["Queue activity is not a heartbeat."] };
const runtime = { snapshot: { currentMode: "observe", currentRuntimeProvider: "telegram" }, effectiveGlobalSafety: { allowed: false, reason: "global_sends_disabled" }, globalAutomation: true, globalSends: false, manualPause: false, guards: [{ module: "Outreach", allowed: false, reason: "global_sends_disabled" }], configurationWarnings: [], warnings: ["Configured state does not prove liveness."] };
const moduleSwitches = { scope: { creatorProfileId: "7", moduleConfiguration: "global_existing_behavior_config" }, globalStatus: { globalAutomation: false, globalSends: false, manualPause: false, runtimeMode: "OFFLINE", heartbeatSummary: { healthy: 1 }, workerHealthSummary: { healthy: 1, stale: 0, failed: 0 }, effectiveSafety: "BLOCKED", reason: "global_automation_disabled" }, masterControl: { key: "global_automation", label: "Autonomous Sales & Messaging", configured: false, effective: "BLOCKED", reason: "Autonomous Sales & Messaging is OFF", lastChanged: "2026-07-19T12:00:00Z", editable: true }, runtime: { configuredMode: "OFFLINE", effectiveMode: "OFFLINE", status: "OFFLINE", lastChanged: "2026-07-19T12:00:00Z", reason: "runtime_offline", editable: true }, cards: { Messaging: [{ key: "telegram_replies", label: "Telegram Replies", configured: true, effective: "BLOCKED", reason: "Autonomous Sales & Messaging is OFF", editable: true, implemented: true }], Sales: [{ key: "mass_ppv", label: "Mass PPV", configured: false, effective: "BLOCKED", reason: "Autonomous Sales & Messaging is OFF", editable: true, implemented: true }], Publishing: [{ key: "telegram_wall", label: "Telegram Wall", configured: false, effective: "BLOCKED", reason: "Autonomous Sales & Messaging is OFF", editable: false, implemented: false }], AI: [{ key: "sales_agent", label: "Sales Agent", configured: true, effective: "ACTIVE", reason: "Always enabled internally", editable: false, implemented: true }] }, deploymentReadiness: [{ key: "fanvue_live_replies", label: "Fanvue Live Replies", status: "BLOCKED", environmentVariable: "ENABLE_REALTIME_FANVUE_SEND", currentValue: "Disabled", source: "Environment", restartRequired: true, description: "Final deployment permit for live Fanvue chat sends.", editable: false }, { key: "telegram_runtime_readiness", label: "Telegram Runtime Readiness", status: "READY", environmentVariable: "TELEGRAM_REPLIES_ENABLED", currentValue: "Enabled", source: "Environment", restartRequired: true, description: "Deployment readiness for Telegram reply processing.", editable: false }] };
const workers = { items: [{ name: "FastAPI", startupType: "Desktop launcher", launcherManaged: true, lastObservedActivity: null, activityEvidence: "Heartbeat persistence", heartbeatAvailable: true, heartbeatStatus: "healthy", instanceId: "fastapi-1", processId: 42, host: "test-host", persistedStatus: "RUNNING", startedAt: "2026-07-19T12:00:00Z", lastHeartbeatAt: "2026-07-19T12:00:00Z", lastPollAt: null, lastSuccessAt: null, lastFailureAt: null, lastError: null, staleThresholdSeconds: 90, attentionReason: null }, { name: "Telegram", startupType: "Separate module process", launcherManaged: false, lastObservedActivity: null, activityEvidence: "No connection heartbeat persistence", heartbeatAvailable: false, heartbeatStatus: "untracked", instanceId: null, processId: null, host: null, persistedStatus: null, startedAt: null, lastHeartbeatAt: null, lastPollAt: null, lastSuccessAt: null, lastFailureAt: null, lastError: null, staleThresholdSeconds: 90, attentionReason: "Heartbeat unavailable; process liveness is untracked." }], summary: { healthy: 1, idle: 0, stale: 0, stopped: 0, failed: 0, untracked: 1 }, warnings: ["Historical activity is not a heartbeat."] };
(workers.items as OperationsWorkers["items"]).push({ ...workers.items[0]!, name: "Outreach", heartbeatStatus: "stale", persistedStatus: "RUNNING", attentionReason: "Last heartbeat exceeded this worker's configured stale threshold." }, { ...workers.items[0]!, name: "Mass PPV", heartbeatStatus: "failed", persistedStatus: "DEGRADED", lastError: "cycle failed", attentionReason: "The worker recorded a failed cycle." });
workers.summary.stale = 1; workers.summary.failed = 1;
const queues = { items: [{ name: "Outreach", total: 2, pending: 0, processing: 1, failed: 1, retryable: 1, stale: 0, recoverable: 0, activeClaims: [{ id: "7", owner: "outreach-worker-1", claimedAt: "2026-07-19T10:00:00Z", leaseExpiresAt: "2026-07-19T10:05:00Z", stale: false }], oldestItem: null, latestCompletion: null, latestFailure: "2026-07-19T11:00:00Z" }], totals: { all: 2, pending: 0, processing: 1, failed: 1, retryable: 1, stale: 0, recoverable: 0 }, warnings: [] };
const publishing = { items: [{ id: "job-1", status: "FAILED", automationState: "NEEDS_ATTENTION", nextRecommendedAction: "Review publishing failure", attention: true, provider: "fanvue", providerStatus: "failed", productId: "product-1", productName: "VIP Set", assetId: 12, uploadStatus: "failed", waitingForMediaLink: false, retryState: "RETRY_REQUIRED", retryCount: 1, failure: "Upload failed", lastAttemptedAt: "2026-07-19T12:00:00Z", updatedAt: "2026-07-19T12:00:00Z" }], summary: { total: 1, queued: 0, uploading: 0, waitingForMediaLink: 0, retry: 1, failed: 1, attention: 1 }, warnings: [] };
const failure = { id: "1", source: "Publishing", status: "failed", error: "Upload failed", timestamp: "2026-07-19T12:00:00Z", retryCount: 1, related: { productId: "product-1" }, evidence: { provider_status: "failed" } };
const failures = { items: [failure], total: 1, warnings: ["Read-only persisted evidence."] };
const recovery = { items: [{ reconciliationId: "rec-1", state: "VERIFIED", attributionState: "UNKNOWN", reason: "MULTIPLE_HARD_MATCHING_CANDIDATES", customer: "Buyer", telegramUserId: 123, fanvueBuyerId: "buyer-uuid", transactionOrderId: "order-1", paymentTimestamp: "2026-07-19T12:00:00Z", amountMinor: 999, currency: "USD", providerResourceId: null, purchaseSource: "media" }] };
const recoveryDetail = { ...recovery.items[0], canManuallyAttribute: true, candidates: [{ purchaseIntentId: "intent-1", offeringId: "offer-1", publicationId: "pub-1", offeringTitle: "Gold Single", offeringType: "SINGLE_IMAGE", expectedPriceMinor: 999, currency: "USD", providerResourceId: "link-1", mediaLink: "https://fanvue.com/link-1", presentedAt: "2026-07-19T11:00:00Z", telegramMessageId: 901, telegramDeliveryState: "CONFIRMED", salesSessionId: null, photoshootRelationship: "shoot-1", supportingEvidence: ["Same customer", "Telegram message confirmed"], warnings: [] }] };
const response = (body: unknown, ok = true) => Promise.resolve({ ok, json: () => Promise.resolve(body) } as Response);
const bodies: Record<string, unknown> = { overview, runtime, "module-switches": moduleSwitches, workers, queues, publishing, failures, "purchase-recovery": recovery };
const renderPage = () => render(<MemoryRouter><BusinessOperationsPage /></MemoryRouter>);
afterEach(() => vi.restoreAllMocks());

describe("BusinessOperationsPage", () => {
  it("renders overview evidence without operational controls", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); expect(await screen.findByText("Overall Health")).toBeInTheDocument(); expect(screen.getByText("Healthy Workers")).toBeInTheDocument(); for (const action of ["Start", "Stop", "Retry", "Pause", "Resume"]) expect(screen.queryByRole("button", { name: action })).not.toBeInTheDocument(); });
  it("renders healthy, stale, failed, and untracked heartbeat states", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Workers" })); expect(await screen.findByText("Telegram")).toBeInTheDocument(); expect(screen.getByText("Heartbeat unavailable")).toBeInTheDocument(); expect(screen.getAllByText("Stale").length).toBeGreaterThan(0); expect(screen.getAllByText("Failed").length).toBeGreaterThan(0); expect(screen.queryByText(/^Running$/)).not.toBeInTheDocument(); });
  it("renders queues, publishing, and a read-only failure drawer", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Queues" })); expect(await screen.findByText("Outreach")).toBeInTheDocument(); expect(screen.getByText("outreach-worker-1")).toBeInTheDocument(); expect(screen.getByText("Recoverable")).toBeInTheDocument(); fireEvent.click(screen.getByRole("tab", { name: "Publishing" })); expect(await screen.findByText("VIP Set")).toBeInTheDocument(); fireEvent.click(screen.getByRole("tab", { name: "Failures" })); fireEvent.click(await screen.findByText("Upload failed")); expect(await screen.findByRole("complementary", { name: "Operational failure details" })).toBeInTheDocument(); expect(screen.getByText(/No retry, recovery, or queue mutation/i)).toBeInTheDocument(); });
  it("shows backend errors", async () => { vi.spyOn(globalThis, "fetch").mockImplementation(() => response({ detail: "Operations unavailable." }, false)); renderPage(); expect(await screen.findByRole("alert")).toHaveTextContent("Operations unavailable."); });
  it("renders authoritative Runtime controls above the autonomous master control and saves OBSERVE", async () => { const fetchMock = vi.spyOn(globalThis, "fetch").mockImplementation((input, init) => init?.method === "PATCH" ? response(moduleSwitches) : response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Module Switches" })); const runtimeGroup = await screen.findByRole("group", { name: "Runtime Mode" }); expect(runtimeGroup).toBeInTheDocument(); expect(screen.getByRole("radio", { name: /OFFLINE/ })).toBeChecked(); expect(screen.getByRole("heading", { name: "Creator_OS Runtime" }).closest("section")?.compareDocumentPosition(screen.getByRole("heading", { name: "Autonomous Sales & Messaging" }).closest("section")!)).toBe(Node.DOCUMENT_POSITION_FOLLOWING); fireEvent.click(screen.getByRole("radio", { name: /OBSERVE/ })); expect(fetchMock).toHaveBeenCalledWith("/api/v1/operations/module-switches/runtime", expect.objectContaining({ method: "PATCH", body: JSON.stringify({ value: "OBSERVE" }) })); });

  it("requires confirmation before switching Runtime to LIVE", async () => { const fetchMock = vi.spyOn(globalThis, "fetch").mockImplementation((input, init) => init?.method === "PATCH" ? response(moduleSwitches) : response(bodies[String(input).split("/").pop() || "overview"])); const confirm = vi.spyOn(window, "confirm").mockReturnValueOnce(false).mockReturnValueOnce(true); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Module Switches" })); const live = await screen.findByRole("radio", { name: /LIVE/ }); fireEvent.click(live); expect(confirm).toHaveBeenCalledTimes(1); expect(fetchMock).not.toHaveBeenCalledWith("/api/v1/operations/module-switches/runtime", expect.anything()); fireEvent.click(live); expect(confirm).toHaveBeenCalledTimes(2); expect(fetchMock).toHaveBeenCalledWith("/api/v1/operations/module-switches/runtime", expect.objectContaining({ method: "PATCH", body: JSON.stringify({ value: "LIVE" }) })); });

  it("renders deployment readiness as read-only environment evidence", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Module Switches" })); const readiness = await screen.findByRole("region", { name: "Deployment Readiness" }); expect(readiness).toHaveTextContent("Fanvue Live Replies"); expect(readiness).toHaveTextContent("ENABLE_REALTIME_FANVUE_SEND"); expect(readiness).toHaveTextContent("Not operator controlled"); expect(readiness.querySelector("button")).toBeNull(); expect(screen.getByRole("button", { name: "Toggle Telegram Replies" })).toBeInTheDocument(); });
  it("retains Runtime as internal diagnostics", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Runtime" })); expect(await screen.findByText("Internal Runtime Diagnostics")).toBeInTheDocument(); expect(screen.getByText(/future OBSERVE capability/)).toBeInTheDocument(); expect(screen.getByText(/Autonomous execution is controlled/)).toBeInTheDocument(); });
  it("renders and saves the autonomous execution master control", async () => { const fetchMock = vi.spyOn(globalThis, "fetch").mockImplementation((input, init) => init?.method === "PATCH" ? response(moduleSwitches) : response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Module Switches" })); expect((await screen.findAllByText("Autonomous Sales & Messaging")).length).toBeGreaterThan(0); expect(screen.getByText(/Workers remain online/)).toBeInTheDocument(); expect(screen.getAllByText("Autonomous Sales & Messaging is OFF").length).toBeGreaterThan(0); fireEvent.click(screen.getByRole("button", { name: "Toggle Autonomous Sales & Messaging" })); expect(await screen.findByRole("status")).toHaveTextContent("Autonomous Sales & Messaging updated"); expect(fetchMock).toHaveBeenCalledWith("/api/v1/operations/module-switches/global_automation", expect.objectContaining({ method: "PATCH", body: JSON.stringify({ value: true }) })); });
  it("shows Commerce Mode as read only and points to Creator Intelligence", async () => { vi.spyOn(globalThis, "fetch").mockImplementation((input) => response(bodies[String(input).split("/").pop() || "overview"])); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Module Switches" })); expect(await screen.findByText("Commerce Mode is managed from Creator Intelligence Center.")).toBeInTheDocument(); expect(screen.queryByRole("group", { name: "Commerce Mode" })).not.toBeInTheDocument(); });
  it("requires review, candidate selection, and confirmation before manual attribution", async () => { const confirm = vi.spyOn(window, "confirm").mockReturnValue(true); const fetchMock = vi.spyOn(globalThis, "fetch").mockImplementation((input, init) => { const url = String(input); if (init?.method === "POST") return response({ success: true, idempotentReplay: false }); if (url.endsWith("/rec-1")) return response(recoveryDetail); if (url.endsWith("/purchase-recovery")) return response(recovery); return response(overview); }); renderPage(); await screen.findByText("Overall Health"); fireEvent.click(screen.getByRole("tab", { name: "Purchase Recovery" })); fireEvent.click(await screen.findByText("Buyer")); expect(await screen.findByRole("complementary", { name: "Purchase recovery review" })).toHaveTextContent("Telegram message confirmed"); const button = screen.getByRole("button", { name: "Attribute Purchase" }); expect(button).toBeDisabled(); fireEvent.click(screen.getByRole("radio")); expect(button).toBeEnabled(); fireEvent.click(button); expect(confirm).toHaveBeenCalledOnce(); expect(fetchMock).toHaveBeenCalledWith("/api/v1/operations/purchase-recovery/rec-1/attribute", expect.objectContaining({ method: "POST" })); });
});
