import { useEffect, useState } from "react";
import { AlertTriangle, X } from "lucide-react";
import { operationsApi } from "./api";
import type { ModuleSwitch, OperationsFailure, OperationsFailures, OperationsModuleSwitches, OperationsOverview, OperationsPublishing, OperationsQueues, OperationsRuntime, OperationsWorkers } from "./types";
import "./business-operations.css";
import "./module-switches.css";

type Tab = "overview" | "runtime" | "module_switches" | "workers" | "queues" | "publishing" | "failures";
type Data = OperationsOverview | OperationsRuntime | OperationsModuleSwitches | OperationsWorkers | OperationsQueues | OperationsPublishing | OperationsFailures;
const tabs: Array<[Tab, string]> = [["overview", "Overview"], ["runtime", "Runtime"], ["module_switches", "Module Switches"], ["workers", "Workers"], ["queues", "Queues"], ["publishing", "Publishing"], ["failures", "Failures"]];
const title = (value: unknown) => { const text = String(value ?? "Untracked"); return text.includes(" ") ? text : text.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase()); };
const when = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "Untracked";
const state = (value: boolean) => value ? "Enabled" : "Disabled";

export function BusinessOperationsPage() {
  const [tab, setTab] = useState<Tab>("overview"); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<OperationsFailure | null>(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); setData(null); operationsApi[tab](controller.signal).then((result) => { if (!controller.signal.aborted) setData(result); }).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Unable to load Operations workspace."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [tab]);
  return <section className="business-operations-page">
    <header className="page-header"><div><p className="page-header__eyebrow">Business operations</p><h1>Operations</h1><p className="page-header__description">Read-only evidence for runtime configuration, queues, publishing, and operational failures.</p></div></header>
    <nav aria-label="Operations workspace sections" className="operations-tabs">{tabs.map(([value, label]) => <button aria-selected={tab === value} className={tab === value ? "is-active" : ""} key={value} onClick={() => { setSelected(null); setData(null); setTab(value); }} role="tab">{label}</button>)}</nav>
    {error && <div className="operations-state operations-state--error" role="alert"><AlertTriangle size={18} />{error}</div>}{loading && <div className="operations-state">Loading persisted operational evidence…</div>}
    {!loading && data && tab === "overview" && <Overview data={data as OperationsOverview} />}
    {!loading && data && tab === "runtime" && <Runtime data={data as OperationsRuntime} />}
    {!loading && data && tab === "module_switches" && <ModuleSwitches data={data as OperationsModuleSwitches} changed={setData} />}
    {!loading && data && tab === "workers" && <Workers data={data as OperationsWorkers} />}
    {!loading && data && tab === "queues" && <Queues data={data as OperationsQueues} />}
    {!loading && data && tab === "publishing" && <Publishing data={data as OperationsPublishing} />}
    {!loading && data && tab === "failures" && <Failures data={data as OperationsFailures} select={setSelected} />}
    {selected && <FailureDrawer failure={selected} close={() => setSelected(null)} />}
  </section>;
}

function Overview({ data }: { data: OperationsOverview }) { return <div className="operations-panel"><Metrics values={[["Overall Health", title(data.overallHealth)], ["Health Score", data.healthScore], ["Database", title(data.database.status)], ["Autonomous Sales & Messaging", data.autonomousExecution], ["Global Sends", state(data.globalSends)], ["Healthy Workers", data.workerCounts.healthy ?? 0], ["Stale Workers", data.workerCounts.stale ?? 0], ["Failed Workers", data.workerCounts.failed ?? 0], ["Untracked Capabilities", data.workerCounts.untracked ?? 0], ["Queued", data.queueTotals.pending ?? 0], ["Failures", data.failureCount], ["Publishing Attention", data.publishingAttention]]} />{data.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<section className="operations-card"><h2>Provider Warnings</h2>{data.providerWarnings.length ? data.providerWarnings.map((warning) => <p key={warning.name}><strong>{warning.name}</strong> · {warning.summary}</p>) : <p>No persisted provider configuration warnings.</p>}</section></div>; }
function Runtime({ data }: { data: OperationsRuntime }) { return <div className="operations-panel"><div className="operations-warning"><span><strong>Internal Runtime Diagnostics</strong><br />Runtime Mode is retained for compatibility, diagnostics, and future OBSERVE capability. Autonomous execution is controlled by Autonomous Sales & Messaging.</span></div><Metrics values={[["Internal Mode", title(data.snapshot.currentMode)], ["Runtime Provider", title(data.snapshot.currentRuntimeProvider)], ["Global Automation", state(data.globalAutomation)], ["Global Sends", state(data.globalSends)], ["Manual Pause", state(data.manualPause)], ["Effective Global Safety", data.effectiveGlobalSafety.allowed ? "Allowed" : "Blocked"]]} />{data.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<div className="operations-grid"><section className="operations-card"><h2>Runtime Snapshot</h2><Definition data={data.snapshot} /></section><section className="operations-card"><h2>Effective Send Guards</h2>{data.guards.map((guard) => <div className="operations-guard" key={guard.module}><strong>{guard.module}</strong><span className={guard.allowed ? "is-good" : "needs-attention"}>{guard.allowed ? "Allowed" : "Blocked"}</span><small>{guard.reason ? title(guard.reason) : "No block recorded"}</small></div>)}</section><section className="operations-card"><h2>Configuration Warnings</h2>{data.configurationWarnings.length ? data.configurationWarnings.map((warning) => <p key={warning.name}>{warning.name}: {warning.summary}</p>) : <p>No configuration warnings.</p>}</section></div></div>; }
function ModuleSwitches({ data, changed }: { data: OperationsModuleSwitches; changed: (data: Data) => void }) {
  const [saving, setSaving] = useState(""); const [message, setMessage] = useState(""); const [saveError, setSaveError] = useState("");
  const update = async (key: string, value: boolean | string) => { setSaving(key); setMessage(""); setSaveError(""); try { changed(await operationsApi.updateModuleSwitch(key, value)); setMessage(`${key === "global_automation" ? "Autonomous Sales & Messaging" : title(key)} updated.`); } catch (reason) { setSaveError(reason instanceof Error ? reason.message : "Unable to update module switch."); } finally { setSaving(""); } };
  const health = data.globalStatus.workerHealthSummary;
  const master = data.masterControl;
  return <div className="operations-panel module-switches"><section className="operations-card module-switches__master"><div><p className="page-header__eyebrow">Master autonomous execution control</p><h2>{master.label}</h2><div className="module-switches__master-states"><span>Configured: <strong>{master.configured ? "ON" : "OFF"}</strong></span><span>Effective: <strong className={master.effective === "ACTIVE" ? "is-good" : "needs-attention"}>{master.effective}</strong></span><span>Reason: <strong>{master.reason ? title(master.reason) : "No block recorded"}</strong></span><span>Last changed: <strong>{master.lastChanged ? new Date(master.lastChanged).toLocaleString() : "Unavailable"}</strong></span></div></div><button className={master.configured ? "is-on" : "is-off"} disabled={Boolean(saving)} aria-label="Toggle Autonomous Sales & Messaging" onClick={() => update(master.key, !master.configured)}>{saving === master.key ? "Saving…" : master.configured ? "Turn Off" : "Turn On"}</button></section>
    {!master.configured && <div className="operations-warning module-switches__off-banner"><AlertTriangle size={16} /><span>Autonomous sales and messaging are disabled. Workers remain online, but no autonomous messages or sales actions will execute.</span></div>}
    <Metrics values={[["Autonomous Sales & Messaging", master.effective], ["Global Sends", state(data.globalStatus.globalSends)], ["Manual Pause", data.globalStatus.manualPause ? "Paused" : "Clear"], ["Healthy Workers", health.healthy ?? 0], ["Stale / Failed", (health.stale ?? 0) + (health.failed ?? 0)]]} />
    {data.globalStatus.effectiveSafety === "BLOCKED" && <Warning>Effective safety is blocked: {title(data.globalStatus.reason)}</Warning>}
    {message && <div className="module-switches__success" role="status">{message}</div>}{saveError && <div className="operations-state operations-state--error" role="alert">{saveError}</div>}
    <div className="module-switches__grid">{(["Messaging", "Sales", "Publishing", "AI"] as const).map((card) => <section className="operations-card module-switch-card" key={card}><h2>{card}</h2>{data.cards[card].map((item) => <SwitchRow item={item} disabled={Boolean(saving)} key={item.key} save={update} saving={saving === item.key} />)}</section>)}</div>
    <section aria-label="Deployment Readiness" className="operations-card deployment-readiness"><div className="deployment-readiness__header"><div><p className="page-header__eyebrow">Read-only environment evidence</p><h2>Deployment Readiness</h2></div><span>Not operator controlled</span></div><p>These deployment permits remain final execution safeguards. Changes require environment configuration outside this workspace.</p><div className="deployment-readiness__grid">{data.deploymentReadiness.map((item) => <article className="deployment-readiness__card" key={item.key}><div><strong>{item.label}</strong><span className={item.status === "READY" ? "is-good" : "needs-attention"}>{item.status}</span></div><dl><div><dt>Environment variable</dt><dd>{item.environmentVariable}</dd></div><div><dt>Current value</dt><dd>{item.currentValue}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div><div><dt>Restart required</dt><dd>{item.restartRequired ? "Yes" : "No"}</dd></div></dl><p>{item.description}</p></article>)}</div></section>
  </div>;
}
function SwitchRow({ item, disabled, saving, save }: { item: ModuleSwitch; disabled: boolean; saving: boolean; save: (key: string, value: boolean) => void }) { return <div className="module-switch-row"><div><strong>{item.label}</strong><small>Configured: {item.configured ? "ON" : "OFF"}</small><small>Effective: <span className={item.effective === "ACTIVE" ? "is-good" : item.effective === "OFF" ? "" : "needs-attention"}>{title(item.effective)}</span></small><small>Reason: {item.reason ? title(item.reason) : "No block"}</small></div>{item.editable ? <button aria-label={`Toggle ${item.label}`} disabled={disabled} onClick={() => save(item.key, !item.configured)}>{saving ? "Saving…" : item.configured ? "Turn Off" : "Turn On"}</button> : <span className="module-switch-row__info">{item.implemented ? "Informational" : "Not Implemented"}</span>}</div>; }
function Workers({ data }: { data: OperationsWorkers }) { return <div className="operations-panel"><Metrics values={[["Healthy", data.summary.healthy ?? 0], ["Idle", data.summary.idle ?? 0], ["Stale", data.summary.stale ?? 0], ["Stopped", data.summary.stopped ?? 0], ["Failed", data.summary.failed ?? 0], ["Untracked", data.summary.untracked ?? 0]]} />{data.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<div className="operations-list">{data.items.map((worker) => <article className="operations-row operations-worker" key={worker.name}><div><small>Worker</small><strong>{worker.name}</strong><span>{worker.startupType} · {worker.launcherManaged ? "Launcher managed" : "Separate startup"} · {worker.launcherEnabled ? "Enabled" : "Disabled"}</span></div><div><small>Heartbeat</small><strong className={["healthy", "idle"].includes(worker.heartbeatStatus) ? "is-good" : "needs-attention"}>{worker.heartbeatAvailable ? title(worker.heartbeatStatus) : "Untracked"}</strong><span>{worker.heartbeatAvailable ? `${worker.host || "Unknown host"} · PID ${worker.processId ?? "unknown"}` : "Heartbeat unavailable"}</span></div><div><small>Launcher</small><strong>{title(worker.lastLauncherAction)}</strong><span>{worker.expectedStartupMethod || "Startup method unavailable"} · {when(worker.lastLauncherActionAt)}</span></div><div><small>Instance</small><strong>{worker.instanceId || "Untracked"}</strong><span>Persisted: {title(worker.persistedStatus)} · Threshold: {worker.staleThresholdSeconds ? `${worker.staleThresholdSeconds}s` : "N/A"}</span></div><div><small>Heartbeat timestamps</small><strong>Heartbeat: {when(worker.lastHeartbeatAt)}</strong><span>Poll: {when(worker.lastPollAt)} · Success: {when(worker.lastSuccessAt)}</span></div><div><small>Attention</small><strong className={worker.attentionReason || worker.startupFailure || worker.configurationBlocked ? "needs-attention" : "is-good"}>{worker.startupFailure || (worker.configurationBlocked ? "Required configuration blocked startup" : worker.attentionReason) || "No heartbeat attention signal"}</strong><span>{worker.lastError ? `Last error: ${worker.lastError} · ${when(worker.lastFailureAt)}` : `Started: ${when(worker.startedAt)}`}</span></div></article>)}</div></div>; }
function Queues({ data }: { data: OperationsQueues }) { return <div className="operations-panel"><Metrics values={[["All Records", data.totals.all ?? 0], ["Pending", data.totals.pending ?? 0], ["Processing", data.totals.processing ?? 0], ["Failed", data.totals.failed ?? 0], ["Retryable", data.totals.retryable ?? 0], ["Recoverable", data.totals.recoverable ?? 0]]} />{data.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}<div className="operations-list">{data.items.map((queue) => <article className="operations-row operations-queue" key={queue.name}><div><small>Queue</small><strong>{queue.name}</strong><span>{queue.total} records</span></div><div><small>Current evidence</small><strong>{queue.pending} pending · {queue.processing} processing</strong><span>{queue.failed} failed · {queue.retryable} retryable · {queue.recoverable ?? 0} recoverable</span></div><div><small>Claim ownership</small>{(queue.activeClaims ?? []).length ? (queue.activeClaims ?? []).map((claim) => <span key={claim.id}><strong>{claim.owner}</strong> · lease {when(claim.leaseExpiresAt)}{claim.stale ? " · stale" : ""}</span>) : <strong>No active claims</strong>}</div><div><small>Latest completion / failure</small><strong>{when(queue.latestCompletion)}</strong><span>Failure: {when(queue.latestFailure)}</span></div></article>)}</div></div>; }
function Publishing({ data }: { data: OperationsPublishing }) { return <div className="operations-panel"><Metrics values={[["Queue", data.summary.total ?? 0], ["Queued", data.summary.queued ?? 0], ["Uploading", data.summary.uploading ?? 0], ["Waiting for Media Link", data.summary.waitingForMediaLink ?? 0], ["Retry State", data.summary.retry ?? 0], ["Failure", data.summary.failed ?? 0], ["Attention", data.summary.attention ?? 0]]} />{!data.items.length ? <div className="operations-state">No account-scoped Publishing jobs.</div> : <div className="operations-list">{data.items.map((item) => <article className="operations-row operations-publishing" key={item.id}><div><small>Publishing Job</small><strong>{item.productName}</strong><span>{item.id}</span></div><div><small>Automation</small><strong>{title(item.automationState)}</strong><span>{item.nextRecommendedAction}</span></div><div><small>Provider</small><strong>{title(item.provider)}</strong><span>{title(item.providerStatus)} · {title(item.uploadStatus)}</span></div><div><small>Association</small><strong>{item.productId ? `Product ${item.productId}` : "No product"}</strong><span>{item.assetId ? `Asset ${item.assetId}` : "No asset"}</span></div><div><small>Attention evidence</small><strong className={item.attention ? "needs-attention" : "is-good"}>{item.attention ? "Attention" : "No attention flag"}</strong><span>{item.failure || `${title(item.retryState)} · ${when(item.lastAttemptedAt)}`}</span></div></article>)}</div>}</div>; }
function Failures({ data, select }: { data: OperationsFailures; select: (failure: OperationsFailure) => void }) { return <div className="operations-panel">{data.warnings.map((warning) => <Warning key={warning}>{warning}</Warning>)}{!data.items.length ? <div className="operations-state">No persisted operational failures.</div> : <div className="operations-list">{data.items.map((failure, index) => <button className="operations-row operations-failure" key={`${failure.source}-${failure.id}-${index}`} onClick={() => select(failure)}><div><small>Source</small><strong>{failure.source}</strong><span>{failure.id}</span></div><div><small>Status</small><strong className="needs-attention">{title(failure.status)}</strong><span>{when(failure.timestamp)}</span></div><div><small>Failure evidence</small><strong>{failure.error}</strong><span>Retry count: {failure.retryCount}</span></div><div><small>Related</small><span>{Object.entries(failure.related).filter(([, value]) => value).map(([key, value]) => `${title(key)} ${value}`).join(" · ") || "No relationship persisted"}</span></div></button>)}</div>}</div>; }
function FailureDrawer({ failure, close }: { failure: OperationsFailure; close: () => void }) { return <aside aria-label="Operational failure details" className="operations-detail"><header><div><small>Persisted failure</small><h2>{failure.source} · {failure.id}</h2></div><button aria-label="Close failure details" onClick={close}><X /></button></header><div className="operations-detail__body"><section><h3>Failure</h3><Definition data={{ status: failure.status, error: failure.error, timestamp: failure.timestamp, retryCount: failure.retryCount }} /></section><section><h3>Related Evidence</h3><Definition data={failure.related} /></section><section><h3>Persisted Record</h3><pre>{JSON.stringify(failure.evidence, null, 2)}</pre></section><Warning>Read-only evidence. No retry, recovery, or queue mutation is available here.</Warning></div></aside>; }
function Metrics({ values }: { values: Array<[string, unknown]> }) { return <div className="operations-metrics">{values.map(([label, value]) => <article key={label}><span>{label}</span><strong>{String(value ?? "Untracked")}</strong></article>)}</div>; }
function Definition({ data }: { data: Record<string, unknown> }) { return <dl className="operations-definition">{Object.entries(data).map(([key, value]) => <div key={key}><dt>{title(key)}</dt><dd>{typeof value === "object" && value !== null ? JSON.stringify(value) : String(value ?? "Untracked")}</dd></div>)}</dl>; }
function Warning({ children }: { children: React.ReactNode }) { return <div className="operations-warning"><AlertTriangle size={16} />{children}</div>; }
