import type { GenerationRecord } from "../../generation-library/types";
import { LibraryImage } from "../../generation-library/LibraryImage";
import { useState } from "react";
import { PhotoshootImagePreview } from "./PhotoshootImagePreview";

export function CandidatePanel({ current, candidate, continuityWarning, busy, onApprove, onRegenerate, onEdit, onReject }: { current: GenerationRecord; candidate: GenerationRecord | null; continuityWarning?: string; busy: boolean; onApprove: () => void; onRegenerate: () => void; onEdit: () => void; onReject: () => void }) {
  const [preview, setPreview] = useState<{ image: GenerationRecord; label: string } | null>(null);
  if (!candidate) return <section className="photoshoot-card photoshoot-review" aria-labelledby="photoshoot-candidate-title"><header><h2 id="photoshoot-candidate-title">Candidate Review</h2><span>Waiting for the next candidate</span></header><div className="photoshoot-candidate">No candidate generated yet.</div></section>;
  return <section className="photoshoot-card photoshoot-review" aria-labelledby="photoshoot-candidate-title"><header><h2 id="photoshoot-candidate-title">Candidate Review</h2><span>Compare before approval</span></header>{continuityWarning && <div className="photoshoot-continuity-warning" role="status">{continuityWarning}</div>}<div className="photoshoot-candidate-compare"><article><strong>Current Approved Shot</strong><button aria-label="Preview Current Approved Shot" className="photoshoot-candidate-preview" onClick={() => setPreview({ image: current, label: "Current Approved Shot" })} type="button"><LibraryImage record={current} /></button></article><article><strong>Candidate Shot</strong><button aria-label="Preview Candidate Shot" className="photoshoot-candidate-preview" onClick={() => setPreview({ image: candidate, label: "Candidate Shot" })} type="button"><LibraryImage priority record={candidate} /></button></article></div><div className="photoshoot-candidate-actions"><button disabled={busy} onClick={onApprove} type="button">Approve Shot</button><button disabled={busy} onClick={onRegenerate} type="button">Regenerate</button><button disabled={busy} onClick={onEdit} type="button">Edit Prompt</button><button disabled={busy} onClick={onReject} type="button">Reject Shot</button></div>{preview && <PhotoshootImagePreview image={preview.image} label={preview.label} onClose={() => setPreview(null)} />}</section>;
}
