import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
import {MemoryRouter} from "react-router-dom";
import {BusinessCustomersPage} from "./BusinessCustomersPage";

const customer={customerId:"commerce:00000000-0000-0000-0000-000000000042",displayName:"Avery",username:"avery",commercialStatuses:["BUYER","SUBSCRIBER","CUSTOMER"],totalSpendMinor:4200,transactionCount:2,contentPurchaseCount:1,lastActivityAt:"2026-09-01T00:00:00Z",isBuyer:true,isHighValue:false,valueTier:"FIRST_PURCHASE",attentionTier:null,retentionStatus:"ACTIVE_SUBSCRIBER",subscriptionStatus:"ACTIVE",subscriptionPeriodEnd:"2026-09-30T00:00:00Z",activeSalesSession:false,activePurchaseIntent:false,relationshipKey:"telegram:42",hasTelegramRelationship:true,localFanvueUserId:42,transactions:[{transactionId:"tx-1",type:"CONTENT",grossMinor:4200,netMinor:3360,occurredAt:"2026-09-01T00:00:00Z"}],ownership:[]};
const listing={items:[customer],summary:{total:1,buyers:1,activeSubscribers:1,formerSubscribers:0,highValue:0,activeSessions:0},total:1,page:1,pageSize:24,totalPages:1};
const json=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}}));
afterEach(()=>vi.restoreAllMocks());

describe("Verified Customers",()=>{
 it("renders canonical metrics and opens concise details",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(input=>String(input).includes("commerce%3A")?json(customer):json(listing));render(<MemoryRouter><BusinessCustomersPage/></MemoryRouter>);expect(await screen.findByText("Avery")).toBeInTheDocument();expect(screen.getByText("$42.00")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"View details"}));expect(await screen.findByRole("complementary",{name:"Customer details"})).toHaveTextContent("Transaction History");expect(screen.getByRole("link",{name:"View Conversation"})).toHaveAttribute("href","/business/relationships?relationship=telegram%3A42");});
 it("sends supported directory filters and search",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json(listing));render(<MemoryRouter><BusinessCustomersPage/></MemoryRouter>);await screen.findByText("Avery");fireEvent.click(screen.getByRole("button",{name:"Buyers"}));fireEvent.change(screen.getByLabelText("Search Customers"),{target:{value:"avery"}});await waitFor(()=>expect(fetch.mock.calls.some(([input])=>String(input).includes("filter=buyers")&&String(input).includes("search=avery"))).toBe(true));});
 it("contains plain-text server errors without JSON parser leakage",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("service unavailable",{status:500,headers:{"content-type":"text/plain"}}));render(<MemoryRouter><BusinessCustomersPage/></MemoryRouter>);expect(await screen.findByRole("alert")).toHaveTextContent("Unable to load verified Customers.");expect(screen.queryByText(/JSON/)).not.toBeInTheDocument();});
 it("does not show Telegram actions for an unmapped customer",async()=>{const unmapped={...customer,relationshipKey:null,hasTelegramRelationship:false};vi.spyOn(globalThis,"fetch").mockImplementation(input=>String(input).includes("commerce%3A")?json(unmapped):json({...listing,items:[unmapped]}));render(<MemoryRouter><BusinessCustomersPage/></MemoryRouter>);await screen.findByText("Avery");fireEvent.click(screen.getByRole("button",{name:"View details"}));await screen.findByRole("complementary",{name:"Customer details"});expect(screen.queryByRole("link",{name:"View Conversation"})).not.toBeInTheDocument();});
});
