import { useEffect, useState } from "react";
import { ChevronDown, ChevronUp, Pencil, Trash2 } from "lucide-react";
import { PageHeader } from "../../shared/ui/PageHeader";
import "../developer-notes/developerNotes.css";

export type PersistentChecklistSubnote = { id:string; todoId:string; title:string; content:string; completed:boolean; createdAt:string; updatedAt:string };
export type PersistentChecklistItem = { id:string; title:string; createdAt:string; completed:boolean; completedAt:string|null; note:string|null; subnotes?:PersistentChecklistSubnote[] };
export type PersistentChecklistApi = {
  list:()=>Promise<{items:PersistentChecklistItem[]}>; create:(title:string,note:string)=>Promise<PersistentChecklistItem>;
  update:(id:string,changes:{title?:string;completed?:boolean;note?:string|null})=>Promise<PersistentChecklistItem>; delete:(id:string)=>Promise<void>;
  createSubnote?:(todoId:string,title:string,content:string)=>Promise<PersistentChecklistSubnote>;
  updateSubnote?:(todoId:string,subnoteId:string,title:string,content:string)=>Promise<PersistentChecklistSubnote>;
  updateSubnoteCompletion?:(todoId:string,subnoteId:string,completed:boolean)=>Promise<PersistentChecklistSubnote>;
  deleteSubnote?:(todoId:string,subnoteId:string)=>Promise<void>;
};
export type PersistentChecklistCopy = { pageTitle:string;pageDescription:string;sectionTitle:string;sectionDescription:string;newButton:string;addButton:string;detailsLabel:string;singular:string;plural:string;completedVerb:string;incompleteVerb:string;completedDateLabel:string;emptyTitle:string;emptyDescription:string };

const localDate=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));
const localTime=(value:string)=>new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(value));
const ordered=(items:PersistentChecklistItem[])=>[...items].sort((a,b)=>Number(a.completed)-Number(b.completed)||new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()||b.id.localeCompare(a.id));

export function PersistentChecklistPage({api,copy}:{api:PersistentChecklistApi;copy:PersistentChecklistCopy}) {
  const [items,setItems]=useState<PersistentChecklistItem[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState("");
  const [creating,setCreating]=useState(false),[newTitle,setNewTitle]=useState(""),[newNote,setNewNote]=useState("");
  const [editingNote,setEditingNote]=useState<string|null>(null),[noteDraft,setNoteDraft]=useState(""),[deleting,setDeleting]=useState<PersistentChecklistItem|null>(null);
  const [expandedItems,setExpandedItems]=useState<Set<string>>(()=>new Set()),[expandedSubnotes,setExpandedSubnotes]=useState<Set<string>>(()=>new Set());
  const [creatingSubnote,setCreatingSubnote]=useState<string|null>(null),[editingSubnote,setEditingSubnote]=useState<string|null>(null);
  const [editingTitle,setEditingTitle]=useState<string|null>(null),[titleDraft,setTitleDraft]=useState("");
  const [subnoteTitle,setSubnoteTitle]=useState(""),[subnoteContent,setSubnoteContent]=useState("");
  const [deletingSubnote,setDeletingSubnote]=useState<{todoId:string;subnote:PersistentChecklistSubnote}|null>(null);
  const supportsSubnotes=Boolean(api.createSubnote&&api.updateSubnote&&api.updateSubnoteCompletion&&api.deleteSubnote);
  useEffect(()=>{void api.list().then(v=>setItems(ordered(v.items))).catch((r:unknown)=>setError(r instanceof Error?r.message:`Unable to load ${copy.plural}.`)).finally(()=>setLoading(false));},[api,copy.plural]);
  const replace=(updated:PersistentChecklistItem)=>setItems(current=>ordered(current.map(item=>item.id===updated.id?updated:item)));
  const toggle=async(item:PersistentChecklistItem)=>{setSaving(item.id);setError("");try{replace(await api.update(item.id,{completed:!item.completed}));}catch(r){setError(r instanceof Error?r.message:`Unable to update ${copy.singular}.`);}finally{setSaving(null);}};
  const saveNote=async(item:PersistentChecklistItem)=>{setSaving(item.id);setError("");try{replace(await api.update(item.id,{note:noteDraft}));setEditingNote(null);}catch(r){setError(r instanceof Error?r.message:`Unable to save ${copy.detailsLabel.toLowerCase()}.`);}finally{setSaving(null);}};
  const saveTitle=async(item:PersistentChecklistItem)=>{if(!titleDraft.trim())return;setSaving(item.id);setError("");try{replace(await api.update(item.id,{title:titleDraft.trim()}));setEditingTitle(null);}catch(r){setError(r instanceof Error?r.message:`Unable to update ${copy.singular}.`);}finally{setSaving(null);}};
  const create=async()=>{if(!newTitle.trim())return;setSaving("new");setError("");try{const created=await api.create(newTitle.trim(),newNote.trim());setItems(c=>ordered([...c,created]));setCreating(false);setNewTitle("");setNewNote("");}catch(r){setError(r instanceof Error?r.message:`Unable to create ${copy.singular}.`);}finally{setSaving(null);}};
  const remove=async(item:PersistentChecklistItem)=>{setSaving(item.id);setError("");try{await api.delete(item.id);setItems(c=>c.filter(x=>x.id!==item.id));setDeleting(null);if(editingNote===item.id)setEditingNote(null);}catch(r){setError(r instanceof Error?r.message:`Unable to delete ${copy.singular}.`);setDeleting(null);}finally{setSaving(null);}};
  const toggleExpanded=(item:PersistentChecklistItem)=>setExpandedItems(current=>{const next=new Set(current);if(next.has(item.id)){next.delete(item.id);const childIds=new Set((item.subnotes||[]).map(x=>x.id));setExpandedSubnotes(open=>new Set([...open].filter(id=>!childIds.has(id))));setCreatingSubnote(v=>v===item.id?null:v);setEditingSubnote(null);}else next.add(item.id);return next;});
  const toggleSubnote=(id:string)=>setExpandedSubnotes(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
  const createChild=async(item:PersistentChecklistItem)=>{if(!api.createSubnote||!subnoteTitle.trim())return;setSaving(`subnote-new-${item.id}`);setError("");try{const child=await api.createSubnote(item.id,subnoteTitle.trim(),subnoteContent.trim());setItems(c=>c.map(x=>x.id===item.id?{...x,subnotes:[...(x.subnotes||[]),child]}:x));setCreatingSubnote(null);setSubnoteTitle("");setSubnoteContent("");}catch(r){setError(r instanceof Error?r.message:"Unable to create subnote.");}finally{setSaving(null);}};
  const saveChild=async(item:PersistentChecklistItem,child:PersistentChecklistSubnote)=>{if(!api.updateSubnote||!subnoteTitle.trim())return;setSaving(`subnote-${child.id}`);setError("");try{const updated=await api.updateSubnote(item.id,child.id,subnoteTitle.trim(),subnoteContent.trim());setItems(c=>c.map(x=>x.id===item.id?{...x,subnotes:(x.subnotes||[]).map(n=>n.id===updated.id?updated:n)}:x));setEditingSubnote(null);setExpandedSubnotes(open=>{const next=new Set(open);next.delete(child.id);return next;});}catch(r){setError(r instanceof Error?r.message:"Unable to save subnote.");}finally{setSaving(null);}};
  const toggleChildCompletion=async(item:PersistentChecklistItem,child:PersistentChecklistSubnote)=>{if(!api.updateSubnoteCompletion)return;setSaving(`subnote-${child.id}`);setError("");try{const updated=await api.updateSubnoteCompletion(item.id,child.id,!child.completed);setItems(c=>c.map(x=>x.id===item.id?{...x,subnotes:(x.subnotes||[]).map(n=>n.id===updated.id?updated:n)}:x));}catch(r){setError(r instanceof Error?r.message:"Unable to update subnote.");}finally{setSaving(null);}};
  const removeChild=async()=>{if(!api.deleteSubnote||!deletingSubnote)return;const {todoId,subnote}=deletingSubnote;setSaving(`subnote-${subnote.id}`);setError("");try{await api.deleteSubnote(todoId,subnote.id);setItems(c=>c.map(x=>x.id===todoId?{...x,subnotes:(x.subnotes||[]).filter(n=>n.id!==subnote.id)}:x));setExpandedSubnotes(open=>{const next=new Set(open);next.delete(subnote.id);return next;});setDeletingSubnote(null);if(editingSubnote===subnote.id)setEditingSubnote(null);}catch(r){setError(r instanceof Error?r.message:"Unable to delete subnote.");setDeletingSubnote(null);}finally{setSaving(null);}};

  return <section className="developer-notes-page"><PageHeader title={copy.pageTitle} description={copy.pageDescription}/><section className="developer-todos" aria-labelledby="persistent-checklist-title"><header><div><h2 id="persistent-checklist-title">{copy.sectionTitle}</h2><p>{copy.sectionDescription}</p></div><button onClick={()=>setCreating(true)} type="button">{copy.newButton}</button></header>
    {error&&<p className="developer-todos__error" role="alert">{error}</p>}
    {creating&&<div className="developer-todo-editor developer-todo-editor--new"><label>Title<input autoFocus value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><label>{copy.detailsLabel} <span>Optional</span><textarea rows={3} value={newNote} onChange={e=>setNewNote(e.target.value)}/></label><div><button disabled={!newTitle.trim()||saving==="new"} onClick={()=>void create()} type="button">{copy.addButton}</button><button onClick={()=>{setCreating(false);setNewTitle("");setNewNote("");}} type="button">Cancel</button></div></div>}
    {loading?<p className="developer-todos__loading">Loading {copy.plural}…</p>:items.length===0?<div className="developer-todos__empty"><strong>{copy.emptyTitle}</strong><p>{copy.emptyDescription}</p></div>:<ul>{items.map(item=><li className={item.completed?"developer-todo developer-todo--completed":"developer-todo"} key={item.id}><div className="developer-todo__main"><input aria-label={`Mark ${item.title} ${item.completed?copy.incompleteVerb:copy.completedVerb}`} checked={item.completed} disabled={saving===item.id} onChange={()=>void toggle(item)} type="checkbox"/>{editingTitle===item.id?<div className="developer-todo__title-editor"><input aria-label={`Title for ${item.title}`} autoFocus value={titleDraft} onChange={e=>setTitleDraft(e.target.value)}/><div><button disabled={!titleDraft.trim()||saving===item.id} onClick={()=>void saveTitle(item)} type="button">Save</button><button onClick={()=>{setEditingTitle(null);setTitleDraft("");}} type="button">Cancel</button></div></div>:<button aria-controls={`checklist-item-body-${item.id}`} aria-expanded={expandedItems.has(item.id)} aria-label={`Toggle ${item.title}`} className="developer-todo__toggle" onClick={()=>toggleExpanded(item)} type="button"><span><strong>{item.title}</strong><small>Added {localDate(item.createdAt)}</small></span>{expandedItems.has(item.id)?<ChevronUp aria-hidden="true" size={17}/>:<ChevronDown aria-hidden="true" size={17}/>}</button>}<button aria-label={`Edit ${item.title}`} className="developer-todo__edit" disabled={saving===item.id||editingTitle===item.id} onClick={()=>{setEditingTitle(item.id);setTitleDraft(item.title);}} title={`Edit ${copy.singular}`} type="button"><Pencil size={15}/></button><button aria-label={`Delete ${item.title}`} className="developer-todo__delete" disabled={saving===item.id} onClick={()=>setDeleting(item)} title={`Delete ${copy.singular}`} type="button"><Trash2 size={16}/></button></div>
      {expandedItems.has(item.id)&&<div className="developer-todo__body" id={`checklist-item-body-${item.id}`}>{item.completed&&item.completedAt&&<span className="developer-todo__completed-date">{copy.completedDateLabel} {localDate(item.completedAt)}</span>}{supportsSubnotes?<Subnotes item={item} expanded={expandedSubnotes} creating={creatingSubnote===item.id} editing={editingSubnote} title={subnoteTitle} content={subnoteContent} saving={saving} onToggle={toggleSubnote} onToggleCompletion={child=>void toggleChildCompletion(item,child)} onAdd={()=>{setCreatingSubnote(item.id);setSubnoteTitle("");setSubnoteContent("");}} onTitle={setSubnoteTitle} onContent={setSubnoteContent} onCreate={()=>void createChild(item)} onCancelCreate={()=>{setCreatingSubnote(null);setSubnoteTitle("");setSubnoteContent("");}} onEdit={child=>{setExpandedSubnotes(open=>new Set(open).add(child.id));setEditingSubnote(child.id);setSubnoteTitle(child.title);setSubnoteContent(child.content);}} onSave={child=>void saveChild(item,child)} onCancelEdit={()=>setEditingSubnote(null)} onDelete={child=>setDeletingSubnote({todoId:item.id,subnote:child})}/>:<>{item.note&&editingNote!==item.id&&<p className="developer-todo__note">{item.note}</p>}{editingNote===item.id?<div className="developer-todo-editor"><textarea aria-label={`${copy.detailsLabel} for ${item.title}`} autoFocus rows={3} value={noteDraft} onChange={e=>setNoteDraft(e.target.value)}/><div><button disabled={saving===item.id} onClick={()=>void saveNote(item)} type="button">Save</button><button onClick={()=>setEditingNote(null)} type="button">Cancel</button></div></div>:<button className="developer-todo__note-action" onClick={()=>{setEditingNote(item.id);setNoteDraft(item.note||"");}} type="button">{item.note?`Edit ${copy.detailsLabel}`:`Add ${copy.detailsLabel}`}</button>}</>}</div>}</li>)}</ul>}
  </section>{deleting&&<Confirm title={`Delete ${copy.singular}?`} text={`Are you sure you want to permanently delete this ${copy.singular}?`} item={deleting.title} onCancel={()=>setDeleting(null)} onDelete={()=>void remove(deleting)} disabled={saving===deleting.id}/>} {deletingSubnote&&<Confirm title="Delete subnote?" text="Are you sure you want to permanently delete only this subnote?" item={deletingSubnote.subnote.title} onCancel={()=>setDeletingSubnote(null)} onDelete={()=>void removeChild()} disabled={saving===`subnote-${deletingSubnote.subnote.id}`}/>}</section>;
}

type SubnotesProps={item:PersistentChecklistItem;expanded:Set<string>;creating:boolean;editing:string|null;title:string;content:string;saving:string|null;onToggle:(id:string)=>void;onToggleCompletion:(n:PersistentChecklistSubnote)=>void;onAdd:()=>void;onTitle:(v:string)=>void;onContent:(v:string)=>void;onCreate:()=>void;onCancelCreate:()=>void;onEdit:(n:PersistentChecklistSubnote)=>void;onSave:(n:PersistentChecklistSubnote)=>void;onCancelEdit:()=>void;onDelete:(n:PersistentChecklistSubnote)=>void};
function Subnotes(p:SubnotesProps){return <section className="developer-subnotes" aria-label={`Subnotes for ${p.item.title}`}><h3>Subnotes</h3>{(p.item.subnotes||[]).length===0&&<p className="developer-subnotes__empty">No subnotes yet.</p>}<ul>{(p.item.subnotes||[]).map(n=><li className={n.completed?"developer-subnote developer-subnote--completed":"developer-subnote"} key={n.id}><div className="developer-subnote__header"><button aria-label={`Mark subnote ${n.title} ${n.completed?"active":"completed"}`} className="developer-subnote__title" disabled={p.saving===`subnote-${n.id}`} onClick={event=>{event.stopPropagation();p.onToggleCompletion(n);}} type="button"><strong>{n.title}</strong><small>Added {localDate(n.createdAt)} · {localTime(n.createdAt)}</small></button><button aria-expanded={p.expanded.has(n.id)} aria-label={`Toggle subnote ${n.title}`} className="developer-subnote__chevron" onClick={event=>{event.stopPropagation();p.onToggle(n.id);}} type="button">{p.expanded.has(n.id)?<ChevronUp aria-hidden="true" size={16}/>:<ChevronDown aria-hidden="true" size={16}/>}</button><button aria-label={`Edit subnote ${n.title}`} className="developer-subnote__edit" disabled={p.saving===`subnote-${n.id}`} onClick={event=>{event.stopPropagation();p.onEdit(n);}} type="button"><Pencil size={15}/></button><button aria-label={`Delete subnote ${n.title}`} className="developer-subnote__delete" disabled={p.saving===`subnote-${n.id}`} onClick={event=>{event.stopPropagation();p.onDelete(n);}} type="button"><Trash2 size={15}/></button></div>{p.expanded.has(n.id)&&<div className="developer-subnote__body">{p.editing===n.id?<SubnoteEditor title={p.title} content={p.content} titleLabel={`Title for subnote ${n.title}`} notesLabel={`Notes for subnote ${n.title}`} saving={p.saving===`subnote-${n.id}`} onTitle={p.onTitle} onContent={p.onContent} onSave={()=>p.onSave(n)} onCancel={p.onCancelEdit}/>:<p>{n.content||"No additional notes."}</p>}</div>}</li>)}</ul>{p.creating?<SubnoteEditor title={p.title} content={p.content} titleLabel={`New subnote title for ${p.item.title}`} notesLabel={`New subnote notes for ${p.item.title}`} saving={p.saving===`subnote-new-${p.item.id}`} onTitle={p.onTitle} onContent={p.onContent} onSave={p.onCreate} onCancel={p.onCancelCreate}/>:<button className="developer-subnotes__add" onClick={p.onAdd} type="button">+ Add Subnote</button>}</section>}
function SubnoteEditor(p:{title:string;content:string;titleLabel:string;notesLabel:string;saving:boolean;onTitle:(v:string)=>void;onContent:(v:string)=>void;onSave:()=>void;onCancel:()=>void}){return <div className="developer-todo-editor developer-subnote__editor"><label>Title<input aria-label={p.titleLabel} autoFocus value={p.title} onChange={e=>p.onTitle(e.target.value)}/></label><label>Notes <span>Optional</span><textarea aria-label={p.notesLabel} rows={4} value={p.content} onChange={e=>p.onContent(e.target.value)}/></label><div><button disabled={!p.title.trim()||p.saving} onClick={p.onSave} type="button">Save</button><button onClick={p.onCancel} type="button">Cancel</button></div></div>}
function Confirm(p:{title:string;text:string;item:string;disabled:boolean;onCancel:()=>void;onDelete:()=>void}){const id=`confirm-${p.title.replace(/\W/g,"-")}`;return <div className="developer-todo-confirm" role="presentation"><div aria-labelledby={id} aria-modal="true" className="developer-todo-confirm__panel" role="dialog"><h2 id={id}>{p.title}</h2><p>{p.text}</p><strong>{p.item}</strong><div><button disabled={p.disabled} onClick={p.onCancel} type="button">Cancel</button><button className="developer-todo-confirm__delete" disabled={p.disabled} onClick={p.onDelete} type="button">Delete</button></div></div></div>}
